// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/javinizer/javinizer-go/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActressAliasRepositoryInterface creates a new instance of MockActressAliasRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActressAliasRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActressAliasRepositoryInterface {
	mock := &MockActressAliasRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActressAliasRepositoryInterface is an autogenerated mock type for the ActressAliasRepositoryInterface type
type MockActressAliasRepositoryInterface struct {
	mock.Mock
}

type MockActressAliasRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActressAliasRepositoryInterface) EXPECT() *MockActressAliasRepositoryInterface_Expecter {
	return &MockActressAliasRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockActressAliasRepositoryInterface
func (_mock *MockActressAliasRepositoryInterface) Create(alias *models.ActressAlias) error {
	ret := _mock.Called(alias)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.ActressAlias) error); ok {
		r0 = returnFunc(alias)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActressAliasRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockActressAliasRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - alias *models.ActressAlias
func (_e *MockActressAliasRepositoryInterface_Expecter) Create(alias interface{}) *MockActressAliasRepositoryInterface_Create_Call {
	return &MockActressAliasRepositoryInterface_Create_Call{Call: _e.mock.On("Create", alias)}
}

func (_c *MockActressAliasRepositoryInterface_Create_Call) Run(run func(alias *models.ActressAlias)) *MockActressAliasRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.ActressAlias
		if args[0] != nil {
			arg0 = args[0].(*models.ActressAlias)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActressAliasRepositoryInterface_Create_Call) Return(err error) *MockActressAliasRepositoryInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActressAliasRepositoryInterface_Create_Call) RunAndReturn(run func(alias *models.ActressAlias) error) *MockActressAliasRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockActressAliasRepositoryInterface
func (_mock *MockActressAliasRepositoryInterface) Delete(aliasName string) error {
	ret := _mock.Called(aliasName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(aliasName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActressAliasRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockActressAliasRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - aliasName string
func (_e *MockActressAliasRepositoryInterface_Expecter) Delete(aliasName interface{}) *MockActressAliasRepositoryInterface_Delete_Call {
	return &MockActressAliasRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", aliasName)}
}

func (_c *MockActressAliasRepositoryInterface_Delete_Call) Run(run func(aliasName string)) *MockActressAliasRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActressAliasRepositoryInterface_Delete_Call) Return(err error) *MockActressAliasRepositoryInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActressAliasRepositoryInterface_Delete_Call) RunAndReturn(run func(aliasName string) error) *MockActressAliasRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAliasName provides a mock function for the type MockActressAliasRepositoryInterface
func (_mock *MockActressAliasRepositoryInterface) FindByAliasName(aliasName string) (*models.ActressAlias, error) {
	ret := _mock.Called(aliasName)

	if len(ret) == 0 {
		panic("no return value specified for FindByAliasName")
	}

	var r0 *models.ActressAlias
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.ActressAlias, error)); ok {
		return returnFunc(aliasName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.ActressAlias); ok {
		r0 = returnFunc(aliasName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ActressAlias)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(aliasName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActressAliasRepositoryInterface_FindByAliasName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAliasName'
type MockActressAliasRepositoryInterface_FindByAliasName_Call struct {
	*mock.Call
}

// FindByAliasName is a helper method to define mock.On call
//   - aliasName string
func (_e *MockActressAliasRepositoryInterface_Expecter) FindByAliasName(aliasName interface{}) *MockActressAliasRepositoryInterface_FindByAliasName_Call {
	return &MockActressAliasRepositoryInterface_FindByAliasName_Call{Call: _e.mock.On("FindByAliasName", aliasName)}
}

func (_c *MockActressAliasRepositoryInterface_FindByAliasName_Call) Run(run func(aliasName string)) *MockActressAliasRepositoryInterface_FindByAliasName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActressAliasRepositoryInterface_FindByAliasName_Call) Return(actressAlias *models.ActressAlias, err error) *MockActressAliasRepositoryInterface_FindByAliasName_Call {
	_c.Call.Return(actressAlias, err)
	return _c
}

func (_c *MockActressAliasRepositoryInterface_FindByAliasName_Call) RunAndReturn(run func(aliasName string) (*models.ActressAlias, error)) *MockActressAliasRepositoryInterface_FindByAliasName_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCanonicalName provides a mock function for the type MockActressAliasRepositoryInterface
func (_mock *MockActressAliasRepositoryInterface) FindByCanonicalName(canonicalName string) ([]models.ActressAlias, error) {
	ret := _mock.Called(canonicalName)

	if len(ret) == 0 {
		panic("no return value specified for FindByCanonicalName")
	}

	var r0 []models.ActressAlias
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]models.ActressAlias, error)); ok {
		return returnFunc(canonicalName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []models.ActressAlias); ok {
		r0 = returnFunc(canonicalName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ActressAlias)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(canonicalName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActressAliasRepositoryInterface_FindByCanonicalName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCanonicalName'
type MockActressAliasRepositoryInterface_FindByCanonicalName_Call struct {
	*mock.Call
}

// FindByCanonicalName is a helper method to define mock.On call
//   - canonicalName string
func (_e *MockActressAliasRepositoryInterface_Expecter) FindByCanonicalName(canonicalName interface{}) *MockActressAliasRepositoryInterface_FindByCanonicalName_Call {
	return &MockActressAliasRepositoryInterface_FindByCanonicalName_Call{Call: _e.mock.On("FindByCanonicalName", canonicalName)}
}

func (_c *MockActressAliasRepositoryInterface_FindByCanonicalName_Call) Run(run func(canonicalName string)) *MockActressAliasRepositoryInterface_FindByCanonicalName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActressAliasRepositoryInterface_FindByCanonicalName_Call) Return(actressAliass []models.ActressAlias, err error) *MockActressAliasRepositoryInterface_FindByCanonicalName_Call {
	_c.Call.Return(actressAliass, err)
	return _c
}

func (_c *MockActressAliasRepositoryInterface_FindByCanonicalName_Call) RunAndReturn(run func(canonicalName string) ([]models.ActressAlias, error)) *MockActressAliasRepositoryInterface_FindByCanonicalName_Call {
	_c.Call.Return(run)
	return _c
}

// GetAliasMap provides a mock function for the type MockActressAliasRepositoryInterface
func (_mock *MockActressAliasRepositoryInterface) GetAliasMap() (map[string]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAliasMap")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[string]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActressAliasRepositoryInterface_GetAliasMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAliasMap'
type MockActressAliasRepositoryInterface_GetAliasMap_Call struct {
	*mock.Call
}

// GetAliasMap is a helper method to define mock.On call
func (_e *MockActressAliasRepositoryInterface_Expecter) GetAliasMap() *MockActressAliasRepositoryInterface_GetAliasMap_Call {
	return &MockActressAliasRepositoryInterface_GetAliasMap_Call{Call: _e.mock.On("GetAliasMap")}
}

func (_c *MockActressAliasRepositoryInterface_GetAliasMap_Call) Run(run func()) *MockActressAliasRepositoryInterface_GetAliasMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockActressAliasRepositoryInterface_GetAliasMap_Call) Return(stringToString map[string]string, err error) *MockActressAliasRepositoryInterface_GetAliasMap_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockActressAliasRepositoryInterface_GetAliasMap_Call) RunAndReturn(run func() (map[string]string, error)) *MockActressAliasRepositoryInterface_GetAliasMap_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockActressAliasRepositoryInterface
func (_mock *MockActressAliasRepositoryInterface) List() ([]models.ActressAlias, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.ActressAlias
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.ActressAlias, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.ActressAlias); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ActressAlias)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActressAliasRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockActressAliasRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockActressAliasRepositoryInterface_Expecter) List() *MockActressAliasRepositoryInterface_List_Call {
	return &MockActressAliasRepositoryInterface_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockActressAliasRepositoryInterface_List_Call) Run(run func()) *MockActressAliasRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockActressAliasRepositoryInterface_List_Call) Return(actressAliass []models.ActressAlias, err error) *MockActressAliasRepositoryInterface_List_Call {
	_c.Call.Return(actressAliass, err)
	return _c
}

func (_c *MockActressAliasRepositoryInterface_List_Call) RunAndReturn(run func() ([]models.ActressAlias, error)) *MockActressAliasRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockActressAliasRepositoryInterface
func (_mock *MockActressAliasRepositoryInterface) Upsert(alias *models.ActressAlias) error {
	ret := _mock.Called(alias)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.ActressAlias) error); ok {
		r0 = returnFunc(alias)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActressAliasRepositoryInterface_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockActressAliasRepositoryInterface_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - alias *models.ActressAlias
func (_e *MockActressAliasRepositoryInterface_Expecter) Upsert(alias interface{}) *MockActressAliasRepositoryInterface_Upsert_Call {
	return &MockActressAliasRepositoryInterface_Upsert_Call{Call: _e.mock.On("Upsert", alias)}
}

func (_c *MockActressAliasRepositoryInterface_Upsert_Call) Run(run func(alias *models.ActressAlias)) *MockActressAliasRepositoryInterface_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.ActressAlias
		if args[0] != nil {
			arg0 = args[0].(*models.ActressAlias)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActressAliasRepositoryInterface_Upsert_Call) Return(err error) *MockActressAliasRepositoryInterface_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActressAliasRepositoryInterface_Upsert_Call) RunAndReturn(run func(alias *models.ActressAlias) error) *MockActressAliasRepositoryInterface_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
