// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/javinizer/javinizer-go/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAggregatorInterface creates a new instance of MockAggregatorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAggregatorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAggregatorInterface {
	mock := &MockAggregatorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAggregatorInterface is an autogenerated mock type for the AggregatorInterface type
type MockAggregatorInterface struct {
	mock.Mock
}

type MockAggregatorInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAggregatorInterface) EXPECT() *MockAggregatorInterface_Expecter {
	return &MockAggregatorInterface_Expecter{mock: &_m.Mock}
}

// Aggregate provides a mock function for the type MockAggregatorInterface
func (_mock *MockAggregatorInterface) Aggregate(results []*models.ScraperResult) (*models.Movie, string, error) {
	ret := _mock.Called(results)

	if len(ret) == 0 {
		panic("no return value specified for Aggregate")
	}

	var r0 *models.Movie
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]*models.ScraperResult) (*models.Movie, string, error)); ok {
		return returnFunc(results)
	}
	if returnFunc, ok := ret.Get(0).(func([]*models.ScraperResult) *models.Movie); ok {
		r0 = returnFunc(results)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Movie)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]*models.ScraperResult) string); ok {
		r1 = returnFunc(results)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func([]*models.ScraperResult) error); ok {
		r2 = returnFunc(results)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAggregatorInterface_Aggregate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Aggregate'
type MockAggregatorInterface_Aggregate_Call struct {
	*mock.Call
}

// Aggregate is a helper method to define mock.On call
//   - results []*models.ScraperResult
func (_e *MockAggregatorInterface_Expecter) Aggregate(results interface{}) *MockAggregatorInterface_Aggregate_Call {
	return &MockAggregatorInterface_Aggregate_Call{Call: _e.mock.On("Aggregate", results)}
}

func (_c *MockAggregatorInterface_Aggregate_Call) Run(run func(results []*models.ScraperResult)) *MockAggregatorInterface_Aggregate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*models.ScraperResult
		if args[0] != nil {
			arg0 = args[0].([]*models.ScraperResult)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAggregatorInterface_Aggregate_Call) Return(movie *models.Movie, warning string, err error) *MockAggregatorInterface_Aggregate_Call {
	_c.Call.Return(movie, warning, err)
	return _c
}

func (_c *MockAggregatorInterface_Aggregate_Call) RunAndReturn(run func(results []*models.ScraperResult) (*models.Movie, string, error)) *MockAggregatorInterface_Aggregate_Call {
	_c.Call.Return(run)
	return _c
}

// AggregateWithPriority provides a mock function for the type MockAggregatorInterface
func (_mock *MockAggregatorInterface) AggregateWithPriority(results []*models.ScraperResult, customPriority []string) (*models.Movie, string, error) {
	ret := _mock.Called(results, customPriority)

	if len(ret) == 0 {
		panic("no return value specified for AggregateWithPriority")
	}

	var r0 *models.Movie
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]*models.ScraperResult, []string) (*models.Movie, string, error)); ok {
		return returnFunc(results, customPriority)
	}
	if returnFunc, ok := ret.Get(0).(func([]*models.ScraperResult, []string) *models.Movie); ok {
		r0 = returnFunc(results, customPriority)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Movie)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]*models.ScraperResult, []string) string); ok {
		r1 = returnFunc(results, customPriority)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func([]*models.ScraperResult, []string) error); ok {
		r2 = returnFunc(results, customPriority)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAggregatorInterface_AggregateWithPriority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateWithPriority'
type MockAggregatorInterface_AggregateWithPriority_Call struct {
	*mock.Call
}

// AggregateWithPriority is a helper method to define mock.On call
//   - results []*models.ScraperResult
//   - customPriority []string
func (_e *MockAggregatorInterface_Expecter) AggregateWithPriority(results interface{}, customPriority interface{}) *MockAggregatorInterface_AggregateWithPriority_Call {
	return &MockAggregatorInterface_AggregateWithPriority_Call{Call: _e.mock.On("AggregateWithPriority", results, customPriority)}
}

func (_c *MockAggregatorInterface_AggregateWithPriority_Call) Run(run func(results []*models.ScraperResult, customPriority []string)) *MockAggregatorInterface_AggregateWithPriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*models.ScraperResult
		if args[0] != nil {
			arg0 = args[0].([]*models.ScraperResult)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAggregatorInterface_AggregateWithPriority_Call) Return(movie *models.Movie, warning string, err error) *MockAggregatorInterface_AggregateWithPriority_Call {
	_c.Call.Return(movie, warning, err)
	return _c
}

func (_c *MockAggregatorInterface_AggregateWithPriority_Call) RunAndReturn(run func(results []*models.ScraperResult, customPriority []string) (*models.Movie, string, error)) *MockAggregatorInterface_AggregateWithPriority_Call {
	_c.Call.Return(run)
	return _c
}

// GetResolvedPriorities provides a mock function for the type MockAggregatorInterface
func (_mock *MockAggregatorInterface) GetResolvedPriorities() map[string][]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResolvedPriorities")
	}

	var r0 map[string][]string
	if returnFunc, ok := ret.Get(0).(func() map[string][]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}
	return r0
}

// MockAggregatorInterface_GetResolvedPriorities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResolvedPriorities'
type MockAggregatorInterface_GetResolvedPriorities_Call struct {
	*mock.Call
}

// GetResolvedPriorities is a helper method to define mock.On call
func (_e *MockAggregatorInterface_Expecter) GetResolvedPriorities() *MockAggregatorInterface_GetResolvedPriorities_Call {
	return &MockAggregatorInterface_GetResolvedPriorities_Call{Call: _e.mock.On("GetResolvedPriorities")}
}

func (_c *MockAggregatorInterface_GetResolvedPriorities_Call) Run(run func()) *MockAggregatorInterface_GetResolvedPriorities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregatorInterface_GetResolvedPriorities_Call) Return(stringToStrings map[string][]string) *MockAggregatorInterface_GetResolvedPriorities_Call {
	_c.Call.Return(stringToStrings)
	return _c
}

func (_c *MockAggregatorInterface_GetResolvedPriorities_Call) RunAndReturn(run func() map[string][]string) *MockAggregatorInterface_GetResolvedPriorities_Call {
	_c.Call.Return(run)
	return _c
}
