// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/javinizer/javinizer-go/internal/aggregator"
	"github.com/javinizer/javinizer-go/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAggregatorInterface creates a new instance of MockAggregatorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAggregatorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAggregatorInterface {
	mock := &MockAggregatorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAggregatorInterface is an autogenerated mock type for the AggregatorInterface type
type MockAggregatorInterface struct {
	mock.Mock
}

type MockAggregatorInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAggregatorInterface) EXPECT() *MockAggregatorInterface_Expecter {
	return &MockAggregatorInterface_Expecter{mock: &_m.Mock}
}

// Aggregate provides a mock function for the type MockAggregatorInterface
func (_mock *MockAggregatorInterface) Aggregate(results []*models.ScraperResult) (*models.Movie, *aggregator.AggregateResult, error) {
	ret := _mock.Called(results)

	if len(ret) == 0 {
		panic("no return value specified for Aggregate")
	}

	var r0 *models.Movie
	var r1 *aggregator.AggregateResult
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]*models.ScraperResult) (*models.Movie, *aggregator.AggregateResult, error)); ok {
		return returnFunc(results)
	}
	if returnFunc, ok := ret.Get(0).(func([]*models.ScraperResult) *models.Movie); ok {
		r0 = returnFunc(results)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Movie)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]*models.ScraperResult) *aggregator.AggregateResult); ok {
		r1 = returnFunc(results)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*aggregator.AggregateResult)
		}
	}
	if returnFunc, ok := ret.Get(2).(func([]*models.ScraperResult) error); ok {
		r2 = returnFunc(results)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAggregatorInterface_Aggregate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Aggregate'
type MockAggregatorInterface_Aggregate_Call struct {
	*mock.Call
}

// Aggregate is a helper method to define mock.On call
//   - results []*models.ScraperResult
func (_e *MockAggregatorInterface_Expecter) Aggregate(results any) *MockAggregatorInterface_Aggregate_Call {
	return &MockAggregatorInterface_Aggregate_Call{Call: _e.mock.On("Aggregate", results)}
}

func (_c *MockAggregatorInterface_Aggregate_Call) Run(run func(results []*models.ScraperResult)) *MockAggregatorInterface_Aggregate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*models.ScraperResult
		if args[0] != nil {
			arg0 = args[0].([]*models.ScraperResult)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAggregatorInterface_Aggregate_Call) Return(movie *models.Movie, aggregateResult *aggregator.AggregateResult, err error) *MockAggregatorInterface_Aggregate_Call {
	_c.Call.Return(movie, aggregateResult, err)
	return _c
}

func (_c *MockAggregatorInterface_Aggregate_Call) RunAndReturn(run func(results []*models.ScraperResult) (*models.Movie, *aggregator.AggregateResult, error)) *MockAggregatorInterface_Aggregate_Call {
	_c.Call.Return(run)
	return _c
}

// AggregateWithPriority provides a mock function for the type MockAggregatorInterface
func (_mock *MockAggregatorInterface) AggregateWithPriority(results []*models.ScraperResult, customPriority []string) (*models.Movie, *aggregator.AggregateResult, error) {
	ret := _mock.Called(results, customPriority)

	if len(ret) == 0 {
		panic("no return value specified for AggregateWithPriority")
	}

	var r0 *models.Movie
	var r1 *aggregator.AggregateResult
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]*models.ScraperResult, []string) (*models.Movie, *aggregator.AggregateResult, error)); ok {
		return returnFunc(results, customPriority)
	}
	if returnFunc, ok := ret.Get(0).(func([]*models.ScraperResult, []string) *models.Movie); ok {
		r0 = returnFunc(results, customPriority)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Movie)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]*models.ScraperResult, []string) *aggregator.AggregateResult); ok {
		r1 = returnFunc(results, customPriority)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*aggregator.AggregateResult)
		}
	}
	if returnFunc, ok := ret.Get(2).(func([]*models.ScraperResult, []string) error); ok {
		r2 = returnFunc(results, customPriority)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAggregatorInterface_AggregateWithPriority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateWithPriority'
type MockAggregatorInterface_AggregateWithPriority_Call struct {
	*mock.Call
}

// AggregateWithPriority is a helper method to define mock.On call
//   - results []*models.ScraperResult
//   - customPriority []string
func (_e *MockAggregatorInterface_Expecter) AggregateWithPriority(results any, customPriority any) *MockAggregatorInterface_AggregateWithPriority_Call {
	return &MockAggregatorInterface_AggregateWithPriority_Call{Call: _e.mock.On("AggregateWithPriority", results, customPriority)}
}

func (_c *MockAggregatorInterface_AggregateWithPriority_Call) Run(run func(results []*models.ScraperResult, customPriority []string)) *MockAggregatorInterface_AggregateWithPriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*models.ScraperResult
		if args[0] != nil {
			arg0 = args[0].([]*models.ScraperResult)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAggregatorInterface_AggregateWithPriority_Call) Return(movie *models.Movie, aggregateResult *aggregator.AggregateResult, err error) *MockAggregatorInterface_AggregateWithPriority_Call {
	_c.Call.Return(movie, aggregateResult, err)
	return _c
}

func (_c *MockAggregatorInterface_AggregateWithPriority_Call) RunAndReturn(run func(results []*models.ScraperResult, customPriority []string) (*models.Movie, *aggregator.AggregateResult, error)) *MockAggregatorInterface_AggregateWithPriority_Call {
	_c.Call.Return(run)
	return _c
}

// ReloadReplacementCaches provides a mock function for the type MockAggregatorInterface
func (_mock *MockAggregatorInterface) ReloadReplacementCaches(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockAggregatorInterface_ReloadReplacementCaches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReloadReplacementCaches'
type MockAggregatorInterface_ReloadReplacementCaches_Call struct {
	*mock.Call
}

// ReloadReplacementCaches is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAggregatorInterface_Expecter) ReloadReplacementCaches(ctx any) *MockAggregatorInterface_ReloadReplacementCaches_Call {
	return &MockAggregatorInterface_ReloadReplacementCaches_Call{Call: _e.mock.On("ReloadReplacementCaches", ctx)}
}

func (_c *MockAggregatorInterface_ReloadReplacementCaches_Call) Run(run func(ctx context.Context)) *MockAggregatorInterface_ReloadReplacementCaches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAggregatorInterface_ReloadReplacementCaches_Call) Return() *MockAggregatorInterface_ReloadReplacementCaches_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAggregatorInterface_ReloadReplacementCaches_Call) RunAndReturn(run func(ctx context.Context)) *MockAggregatorInterface_ReloadReplacementCaches_Call {
	_c.Run(run)
	return _c
}
