// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/javinizer/javinizer-go/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBatchFileOperationRepositoryInterface creates a new instance of MockBatchFileOperationRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBatchFileOperationRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBatchFileOperationRepositoryInterface {
	mock := &MockBatchFileOperationRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBatchFileOperationRepositoryInterface is an autogenerated mock type for the BatchFileOperationRepositoryInterface type
type MockBatchFileOperationRepositoryInterface struct {
	mock.Mock
}

type MockBatchFileOperationRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBatchFileOperationRepositoryInterface) EXPECT() *MockBatchFileOperationRepositoryInterface_Expecter {
	return &MockBatchFileOperationRepositoryInterface_Expecter{mock: &_m.Mock}
}

// CountByBatchJobID provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) CountByBatchJobID(ctx context.Context, batchJobID string) (int64, error) {
	ret := _mock.Called(ctx, batchJobID)

	if len(ret) == 0 {
		panic("no return value specified for CountByBatchJobID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, batchJobID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, batchJobID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, batchJobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByBatchJobID'
type MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call struct {
	*mock.Call
}

// CountByBatchJobID is a helper method to define mock.On call
//   - ctx context.Context
//   - batchJobID string
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) CountByBatchJobID(ctx any, batchJobID any) *MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call {
	return &MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call{Call: _e.mock.On("CountByBatchJobID", ctx, batchJobID)}
}

func (_c *MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call) Run(run func(ctx context.Context, batchJobID string)) *MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call) Return(n int64, err error) *MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call) RunAndReturn(run func(ctx context.Context, batchJobID string) (int64, error)) *MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call {
	_c.Call.Return(run)
	return _c
}

// CountByBatchJobIDAndRevertStatus provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) CountByBatchJobIDAndRevertStatus(ctx context.Context, batchJobID string, status models.RevertStatusEnum) (int64, error) {
	ret := _mock.Called(ctx, batchJobID, status)

	if len(ret) == 0 {
		panic("no return value specified for CountByBatchJobIDAndRevertStatus")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.RevertStatusEnum) (int64, error)); ok {
		return returnFunc(ctx, batchJobID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.RevertStatusEnum) int64); ok {
		r0 = returnFunc(ctx, batchJobID, status)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.RevertStatusEnum) error); ok {
		r1 = returnFunc(ctx, batchJobID, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByBatchJobIDAndRevertStatus'
type MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call struct {
	*mock.Call
}

// CountByBatchJobIDAndRevertStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - batchJobID string
//   - status models.RevertStatusEnum
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) CountByBatchJobIDAndRevertStatus(ctx any, batchJobID any, status any) *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call {
	return &MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call{Call: _e.mock.On("CountByBatchJobIDAndRevertStatus", ctx, batchJobID, status)}
}

func (_c *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call) Run(run func(ctx context.Context, batchJobID string, status models.RevertStatusEnum)) *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.RevertStatusEnum
		if args[2] != nil {
			arg2 = args[2].(models.RevertStatusEnum)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call) Return(n int64, err error) *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call) RunAndReturn(run func(ctx context.Context, batchJobID string, status models.RevertStatusEnum) (int64, error)) *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CountByBatchJobIDs provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) CountByBatchJobIDs(ctx context.Context, jobIDs []string) (map[string]int64, error) {
	ret := _mock.Called(ctx, jobIDs)

	if len(ret) == 0 {
		panic("no return value specified for CountByBatchJobIDs")
	}

	var r0 map[string]int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string]int64, error)); ok {
		return returnFunc(ctx, jobIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string]int64); ok {
		r0 = returnFunc(ctx, jobIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, jobIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBatchFileOperationRepositoryInterface_CountByBatchJobIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByBatchJobIDs'
type MockBatchFileOperationRepositoryInterface_CountByBatchJobIDs_Call struct {
	*mock.Call
}

// CountByBatchJobIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - jobIDs []string
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) CountByBatchJobIDs(ctx any, jobIDs any) *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDs_Call {
	return &MockBatchFileOperationRepositoryInterface_CountByBatchJobIDs_Call{Call: _e.mock.On("CountByBatchJobIDs", ctx, jobIDs)}
}

func (_c *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDs_Call) Run(run func(ctx context.Context, jobIDs []string)) *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDs_Call) Return(stringToInt64 map[string]int64, err error) *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDs_Call {
	_c.Call.Return(stringToInt64, err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDs_Call) RunAndReturn(run func(ctx context.Context, jobIDs []string) (map[string]int64, error)) *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDs_Call {
	_c.Call.Return(run)
	return _c
}

// CountRevertedByBatchJobIDs provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) CountRevertedByBatchJobIDs(ctx context.Context, jobIDs []string) (map[string]int64, error) {
	ret := _mock.Called(ctx, jobIDs)

	if len(ret) == 0 {
		panic("no return value specified for CountRevertedByBatchJobIDs")
	}

	var r0 map[string]int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string]int64, error)); ok {
		return returnFunc(ctx, jobIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string]int64); ok {
		r0 = returnFunc(ctx, jobIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, jobIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBatchFileOperationRepositoryInterface_CountRevertedByBatchJobIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountRevertedByBatchJobIDs'
type MockBatchFileOperationRepositoryInterface_CountRevertedByBatchJobIDs_Call struct {
	*mock.Call
}

// CountRevertedByBatchJobIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - jobIDs []string
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) CountRevertedByBatchJobIDs(ctx any, jobIDs any) *MockBatchFileOperationRepositoryInterface_CountRevertedByBatchJobIDs_Call {
	return &MockBatchFileOperationRepositoryInterface_CountRevertedByBatchJobIDs_Call{Call: _e.mock.On("CountRevertedByBatchJobIDs", ctx, jobIDs)}
}

func (_c *MockBatchFileOperationRepositoryInterface_CountRevertedByBatchJobIDs_Call) Run(run func(ctx context.Context, jobIDs []string)) *MockBatchFileOperationRepositoryInterface_CountRevertedByBatchJobIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CountRevertedByBatchJobIDs_Call) Return(stringToInt64 map[string]int64, err error) *MockBatchFileOperationRepositoryInterface_CountRevertedByBatchJobIDs_Call {
	_c.Call.Return(stringToInt64, err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CountRevertedByBatchJobIDs_Call) RunAndReturn(run func(ctx context.Context, jobIDs []string) (map[string]int64, error)) *MockBatchFileOperationRepositoryInterface_CountRevertedByBatchJobIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) Create(ctx context.Context, op *models.BatchFileOperation) error {
	ret := _mock.Called(ctx, op)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.BatchFileOperation) error); ok {
		r0 = returnFunc(ctx, op)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatchFileOperationRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBatchFileOperationRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - op *models.BatchFileOperation
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) Create(ctx any, op any) *MockBatchFileOperationRepositoryInterface_Create_Call {
	return &MockBatchFileOperationRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, op)}
}

func (_c *MockBatchFileOperationRepositoryInterface_Create_Call) Run(run func(ctx context.Context, op *models.BatchFileOperation)) *MockBatchFileOperationRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.BatchFileOperation
		if args[1] != nil {
			arg1 = args[1].(*models.BatchFileOperation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_Create_Call) Return(err error) *MockBatchFileOperationRepositoryInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, op *models.BatchFileOperation) error) *MockBatchFileOperationRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) CreateBatch(ctx context.Context, ops []*models.BatchFileOperation) error {
	ret := _mock.Called(ctx, ops)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*models.BatchFileOperation) error); ok {
		r0 = returnFunc(ctx, ops)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatchFileOperationRepositoryInterface_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockBatchFileOperationRepositoryInterface_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - ops []*models.BatchFileOperation
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) CreateBatch(ctx any, ops any) *MockBatchFileOperationRepositoryInterface_CreateBatch_Call {
	return &MockBatchFileOperationRepositoryInterface_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, ops)}
}

func (_c *MockBatchFileOperationRepositoryInterface_CreateBatch_Call) Run(run func(ctx context.Context, ops []*models.BatchFileOperation)) *MockBatchFileOperationRepositoryInterface_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*models.BatchFileOperation
		if args[1] != nil {
			arg1 = args[1].([]*models.BatchFileOperation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CreateBatch_Call) Return(err error) *MockBatchFileOperationRepositoryInterface_CreateBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CreateBatch_Call) RunAndReturn(run func(ctx context.Context, ops []*models.BatchFileOperation) error) *MockBatchFileOperationRepositoryInterface_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBatchJobID provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) FindByBatchJobID(ctx context.Context, batchJobID string) ([]models.BatchFileOperation, error) {
	ret := _mock.Called(ctx, batchJobID)

	if len(ret) == 0 {
		panic("no return value specified for FindByBatchJobID")
	}

	var r0 []models.BatchFileOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.BatchFileOperation, error)); ok {
		return returnFunc(ctx, batchJobID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.BatchFileOperation); ok {
		r0 = returnFunc(ctx, batchJobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BatchFileOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, batchJobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBatchJobID'
type MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call struct {
	*mock.Call
}

// FindByBatchJobID is a helper method to define mock.On call
//   - ctx context.Context
//   - batchJobID string
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) FindByBatchJobID(ctx any, batchJobID any) *MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call {
	return &MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call{Call: _e.mock.On("FindByBatchJobID", ctx, batchJobID)}
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call) Run(run func(ctx context.Context, batchJobID string)) *MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call) Return(batchFileOperations []models.BatchFileOperation, err error) *MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call {
	_c.Call.Return(batchFileOperations, err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call) RunAndReturn(run func(ctx context.Context, batchJobID string) ([]models.BatchFileOperation, error)) *MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBatchJobIDAndRevertStatus provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) FindByBatchJobIDAndRevertStatus(ctx context.Context, batchJobID string, revertStatus models.RevertStatusEnum) ([]models.BatchFileOperation, error) {
	ret := _mock.Called(ctx, batchJobID, revertStatus)

	if len(ret) == 0 {
		panic("no return value specified for FindByBatchJobIDAndRevertStatus")
	}

	var r0 []models.BatchFileOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.RevertStatusEnum) ([]models.BatchFileOperation, error)); ok {
		return returnFunc(ctx, batchJobID, revertStatus)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.RevertStatusEnum) []models.BatchFileOperation); ok {
		r0 = returnFunc(ctx, batchJobID, revertStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BatchFileOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.RevertStatusEnum) error); ok {
		r1 = returnFunc(ctx, batchJobID, revertStatus)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBatchJobIDAndRevertStatus'
type MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call struct {
	*mock.Call
}

// FindByBatchJobIDAndRevertStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - batchJobID string
//   - revertStatus models.RevertStatusEnum
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) FindByBatchJobIDAndRevertStatus(ctx any, batchJobID any, revertStatus any) *MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call {
	return &MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call{Call: _e.mock.On("FindByBatchJobIDAndRevertStatus", ctx, batchJobID, revertStatus)}
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call) Run(run func(ctx context.Context, batchJobID string, revertStatus models.RevertStatusEnum)) *MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.RevertStatusEnum
		if args[2] != nil {
			arg2 = args[2].(models.RevertStatusEnum)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call) Return(batchFileOperations []models.BatchFileOperation, err error) *MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call {
	_c.Call.Return(batchFileOperations, err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call) RunAndReturn(run func(ctx context.Context, batchJobID string, revertStatus models.RevertStatusEnum) ([]models.BatchFileOperation, error)) *MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) FindByID(ctx context.Context, id uint) (*models.BatchFileOperation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.BatchFileOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*models.BatchFileOperation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *models.BatchFileOperation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BatchFileOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBatchFileOperationRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBatchFileOperationRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) FindByID(ctx any, id any) *MockBatchFileOperationRepositoryInterface_FindByID_Call {
	return &MockBatchFileOperationRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockBatchFileOperationRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByID_Call) Return(batchFileOperation *models.BatchFileOperation, err error) *MockBatchFileOperationRepositoryInterface_FindByID_Call {
	_c.Call.Return(batchFileOperation, err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uint) (*models.BatchFileOperation, error)) *MockBatchFileOperationRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) Update(ctx context.Context, op *models.BatchFileOperation) error {
	ret := _mock.Called(ctx, op)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.BatchFileOperation) error); ok {
		r0 = returnFunc(ctx, op)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatchFileOperationRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBatchFileOperationRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - op *models.BatchFileOperation
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) Update(ctx any, op any) *MockBatchFileOperationRepositoryInterface_Update_Call {
	return &MockBatchFileOperationRepositoryInterface_Update_Call{Call: _e.mock.On("Update", ctx, op)}
}

func (_c *MockBatchFileOperationRepositoryInterface_Update_Call) Run(run func(ctx context.Context, op *models.BatchFileOperation)) *MockBatchFileOperationRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.BatchFileOperation
		if args[1] != nil {
			arg1 = args[1].(*models.BatchFileOperation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_Update_Call) Return(err error) *MockBatchFileOperationRepositoryInterface_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_Update_Call) RunAndReturn(run func(ctx context.Context, op *models.BatchFileOperation) error) *MockBatchFileOperationRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRevertStatus provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) UpdateRevertStatus(ctx context.Context, id uint, status models.RevertStatusEnum) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRevertStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, models.RevertStatusEnum) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRevertStatus'
type MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call struct {
	*mock.Call
}

// UpdateRevertStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - status models.RevertStatusEnum
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) UpdateRevertStatus(ctx any, id any, status any) *MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call {
	return &MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call{Call: _e.mock.On("UpdateRevertStatus", ctx, id, status)}
}

func (_c *MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call) Run(run func(ctx context.Context, id uint, status models.RevertStatusEnum)) *MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 models.RevertStatusEnum
		if args[2] != nil {
			arg2 = args[2].(models.RevertStatusEnum)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call) Return(err error) *MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call) RunAndReturn(run func(ctx context.Context, id uint, status models.RevertStatusEnum) error) *MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call {
	_c.Call.Return(run)
	return _c
}
