// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/javinizer/javinizer-go/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBatchFileOperationRepositoryInterface creates a new instance of MockBatchFileOperationRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBatchFileOperationRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBatchFileOperationRepositoryInterface {
	mock := &MockBatchFileOperationRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBatchFileOperationRepositoryInterface is an autogenerated mock type for the BatchFileOperationRepositoryInterface type
type MockBatchFileOperationRepositoryInterface struct {
	mock.Mock
}

type MockBatchFileOperationRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBatchFileOperationRepositoryInterface) EXPECT() *MockBatchFileOperationRepositoryInterface_Expecter {
	return &MockBatchFileOperationRepositoryInterface_Expecter{mock: &_m.Mock}
}

// CountByBatchJobID provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) CountByBatchJobID(batchJobID string) (int64, error) {
	ret := _mock.Called(batchJobID)

	if len(ret) == 0 {
		panic("no return value specified for CountByBatchJobID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return returnFunc(batchJobID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int64); ok {
		r0 = returnFunc(batchJobID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(batchJobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByBatchJobID'
type MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call struct {
	*mock.Call
}

// CountByBatchJobID is a helper method to define mock.On call
//   - batchJobID string
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) CountByBatchJobID(batchJobID interface{}) *MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call {
	return &MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call{Call: _e.mock.On("CountByBatchJobID", batchJobID)}
}

func (_c *MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call) Run(run func(batchJobID string)) *MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call) Return(n int64, err error) *MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call) RunAndReturn(run func(batchJobID string) (int64, error)) *MockBatchFileOperationRepositoryInterface_CountByBatchJobID_Call {
	_c.Call.Return(run)
	return _c
}

// CountByBatchJobIDAndRevertStatus provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) CountByBatchJobIDAndRevertStatus(batchJobID string, status string) (int64, error) {
	ret := _mock.Called(batchJobID, status)

	if len(ret) == 0 {
		panic("no return value specified for CountByBatchJobIDAndRevertStatus")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (int64, error)); ok {
		return returnFunc(batchJobID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) int64); ok {
		r0 = returnFunc(batchJobID, status)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(batchJobID, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByBatchJobIDAndRevertStatus'
type MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call struct {
	*mock.Call
}

// CountByBatchJobIDAndRevertStatus is a helper method to define mock.On call
//   - batchJobID string
//   - status string
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) CountByBatchJobIDAndRevertStatus(batchJobID interface{}, status interface{}) *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call {
	return &MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call{Call: _e.mock.On("CountByBatchJobIDAndRevertStatus", batchJobID, status)}
}

func (_c *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call) Run(run func(batchJobID string, status string)) *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call) Return(n int64, err error) *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call) RunAndReturn(run func(batchJobID string, status string) (int64, error)) *MockBatchFileOperationRepositoryInterface_CountByBatchJobIDAndRevertStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) Create(op *models.BatchFileOperation) error {
	ret := _mock.Called(op)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.BatchFileOperation) error); ok {
		r0 = returnFunc(op)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatchFileOperationRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBatchFileOperationRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - op *models.BatchFileOperation
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) Create(op interface{}) *MockBatchFileOperationRepositoryInterface_Create_Call {
	return &MockBatchFileOperationRepositoryInterface_Create_Call{Call: _e.mock.On("Create", op)}
}

func (_c *MockBatchFileOperationRepositoryInterface_Create_Call) Run(run func(op *models.BatchFileOperation)) *MockBatchFileOperationRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.BatchFileOperation
		if args[0] != nil {
			arg0 = args[0].(*models.BatchFileOperation)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_Create_Call) Return(err error) *MockBatchFileOperationRepositoryInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_Create_Call) RunAndReturn(run func(op *models.BatchFileOperation) error) *MockBatchFileOperationRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) CreateBatch(ops []*models.BatchFileOperation) error {
	ret := _mock.Called(ops)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*models.BatchFileOperation) error); ok {
		r0 = returnFunc(ops)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatchFileOperationRepositoryInterface_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockBatchFileOperationRepositoryInterface_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ops []*models.BatchFileOperation
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) CreateBatch(ops interface{}) *MockBatchFileOperationRepositoryInterface_CreateBatch_Call {
	return &MockBatchFileOperationRepositoryInterface_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ops)}
}

func (_c *MockBatchFileOperationRepositoryInterface_CreateBatch_Call) Run(run func(ops []*models.BatchFileOperation)) *MockBatchFileOperationRepositoryInterface_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*models.BatchFileOperation
		if args[0] != nil {
			arg0 = args[0].([]*models.BatchFileOperation)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CreateBatch_Call) Return(err error) *MockBatchFileOperationRepositoryInterface_CreateBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_CreateBatch_Call) RunAndReturn(run func(ops []*models.BatchFileOperation) error) *MockBatchFileOperationRepositoryInterface_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBatchJobID provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) FindByBatchJobID(batchJobID string) ([]models.BatchFileOperation, error) {
	ret := _mock.Called(batchJobID)

	if len(ret) == 0 {
		panic("no return value specified for FindByBatchJobID")
	}

	var r0 []models.BatchFileOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]models.BatchFileOperation, error)); ok {
		return returnFunc(batchJobID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []models.BatchFileOperation); ok {
		r0 = returnFunc(batchJobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BatchFileOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(batchJobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBatchJobID'
type MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call struct {
	*mock.Call
}

// FindByBatchJobID is a helper method to define mock.On call
//   - batchJobID string
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) FindByBatchJobID(batchJobID interface{}) *MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call {
	return &MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call{Call: _e.mock.On("FindByBatchJobID", batchJobID)}
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call) Run(run func(batchJobID string)) *MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call) Return(batchFileOperations []models.BatchFileOperation, err error) *MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call {
	_c.Call.Return(batchFileOperations, err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call) RunAndReturn(run func(batchJobID string) ([]models.BatchFileOperation, error)) *MockBatchFileOperationRepositoryInterface_FindByBatchJobID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBatchJobIDAndRevertStatus provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) FindByBatchJobIDAndRevertStatus(batchJobID string, revertStatus string) ([]models.BatchFileOperation, error) {
	ret := _mock.Called(batchJobID, revertStatus)

	if len(ret) == 0 {
		panic("no return value specified for FindByBatchJobIDAndRevertStatus")
	}

	var r0 []models.BatchFileOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]models.BatchFileOperation, error)); ok {
		return returnFunc(batchJobID, revertStatus)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []models.BatchFileOperation); ok {
		r0 = returnFunc(batchJobID, revertStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BatchFileOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(batchJobID, revertStatus)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBatchJobIDAndRevertStatus'
type MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call struct {
	*mock.Call
}

// FindByBatchJobIDAndRevertStatus is a helper method to define mock.On call
//   - batchJobID string
//   - revertStatus string
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) FindByBatchJobIDAndRevertStatus(batchJobID interface{}, revertStatus interface{}) *MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call {
	return &MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call{Call: _e.mock.On("FindByBatchJobIDAndRevertStatus", batchJobID, revertStatus)}
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call) Run(run func(batchJobID string, revertStatus string)) *MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call) Return(batchFileOperations []models.BatchFileOperation, err error) *MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call {
	_c.Call.Return(batchFileOperations, err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call) RunAndReturn(run func(batchJobID string, revertStatus string) ([]models.BatchFileOperation, error)) *MockBatchFileOperationRepositoryInterface_FindByBatchJobIDAndRevertStatus_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) FindByID(id uint) (*models.BatchFileOperation, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.BatchFileOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*models.BatchFileOperation, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *models.BatchFileOperation); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BatchFileOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBatchFileOperationRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBatchFileOperationRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) FindByID(id interface{}) *MockBatchFileOperationRepositoryInterface_FindByID_Call {
	return &MockBatchFileOperationRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByID_Call) Run(run func(id uint)) *MockBatchFileOperationRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByID_Call) Return(batchFileOperation *models.BatchFileOperation, err error) *MockBatchFileOperationRepositoryInterface_FindByID_Call {
	_c.Call.Return(batchFileOperation, err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_FindByID_Call) RunAndReturn(run func(id uint) (*models.BatchFileOperation, error)) *MockBatchFileOperationRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) Update(op *models.BatchFileOperation) error {
	ret := _mock.Called(op)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.BatchFileOperation) error); ok {
		r0 = returnFunc(op)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatchFileOperationRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBatchFileOperationRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - op *models.BatchFileOperation
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) Update(op interface{}) *MockBatchFileOperationRepositoryInterface_Update_Call {
	return &MockBatchFileOperationRepositoryInterface_Update_Call{Call: _e.mock.On("Update", op)}
}

func (_c *MockBatchFileOperationRepositoryInterface_Update_Call) Run(run func(op *models.BatchFileOperation)) *MockBatchFileOperationRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.BatchFileOperation
		if args[0] != nil {
			arg0 = args[0].(*models.BatchFileOperation)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_Update_Call) Return(err error) *MockBatchFileOperationRepositoryInterface_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_Update_Call) RunAndReturn(run func(op *models.BatchFileOperation) error) *MockBatchFileOperationRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRevertStatus provides a mock function for the type MockBatchFileOperationRepositoryInterface
func (_mock *MockBatchFileOperationRepositoryInterface) UpdateRevertStatus(id uint, status string) error {
	ret := _mock.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRevertStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, string) error); ok {
		r0 = returnFunc(id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRevertStatus'
type MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call struct {
	*mock.Call
}

// UpdateRevertStatus is a helper method to define mock.On call
//   - id uint
//   - status string
func (_e *MockBatchFileOperationRepositoryInterface_Expecter) UpdateRevertStatus(id interface{}, status interface{}) *MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call {
	return &MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call{Call: _e.mock.On("UpdateRevertStatus", id, status)}
}

func (_c *MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call) Run(run func(id uint, status string)) *MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call) Return(err error) *MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call) RunAndReturn(run func(id uint, status string) error) *MockBatchFileOperationRepositoryInterface_UpdateRevertStatus_Call {
	_c.Call.Return(run)
	return _c
}
