// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/javinizer/javinizer-go/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDownloadProxyResolver creates a new instance of MockDownloadProxyResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDownloadProxyResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDownloadProxyResolver {
	mock := &MockDownloadProxyResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDownloadProxyResolver is an autogenerated mock type for the DownloadProxyResolver type
type MockDownloadProxyResolver struct {
	mock.Mock
}

type MockDownloadProxyResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDownloadProxyResolver) EXPECT() *MockDownloadProxyResolver_Expecter {
	return &MockDownloadProxyResolver_Expecter{mock: &_m.Mock}
}

// ResolveDownloadProxyForHost provides a mock function for the type MockDownloadProxyResolver
func (_mock *MockDownloadProxyResolver) ResolveDownloadProxyForHost(host string) (*models.ProxyConfig, *models.ProxyConfig, bool) {
	ret := _mock.Called(host)

	if len(ret) == 0 {
		panic("no return value specified for ResolveDownloadProxyForHost")
	}

	var r0 *models.ProxyConfig
	var r1 *models.ProxyConfig
	var r2 bool
	if returnFunc, ok := ret.Get(0).(func(string) (*models.ProxyConfig, *models.ProxyConfig, bool)); ok {
		return returnFunc(host)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.ProxyConfig); ok {
		r0 = returnFunc(host)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ProxyConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *models.ProxyConfig); ok {
		r1 = returnFunc(host)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.ProxyConfig)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string) bool); ok {
		r2 = returnFunc(host)
	} else {
		r2 = ret.Get(2).(bool)
	}
	return r0, r1, r2
}

// MockDownloadProxyResolver_ResolveDownloadProxyForHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveDownloadProxyForHost'
type MockDownloadProxyResolver_ResolveDownloadProxyForHost_Call struct {
	*mock.Call
}

// ResolveDownloadProxyForHost is a helper method to define mock.On call
//   - host string
func (_e *MockDownloadProxyResolver_Expecter) ResolveDownloadProxyForHost(host any) *MockDownloadProxyResolver_ResolveDownloadProxyForHost_Call {
	return &MockDownloadProxyResolver_ResolveDownloadProxyForHost_Call{Call: _e.mock.On("ResolveDownloadProxyForHost", host)}
}

func (_c *MockDownloadProxyResolver_ResolveDownloadProxyForHost_Call) Run(run func(host string)) *MockDownloadProxyResolver_ResolveDownloadProxyForHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDownloadProxyResolver_ResolveDownloadProxyForHost_Call) Return(downloadOverride *models.ProxyConfig, scraperProxy *models.ProxyConfig, handled bool) *MockDownloadProxyResolver_ResolveDownloadProxyForHost_Call {
	_c.Call.Return(downloadOverride, scraperProxy, handled)
	return _c
}

func (_c *MockDownloadProxyResolver_ResolveDownloadProxyForHost_Call) RunAndReturn(run func(host string) (*models.ProxyConfig, *models.ProxyConfig, bool)) *MockDownloadProxyResolver_ResolveDownloadProxyForHost_Call {
	_c.Call.Return(run)
	return _c
}
