// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/javinizer/javinizer-go/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGenreReplacementRepositoryInterface creates a new instance of MockGenreReplacementRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenreReplacementRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenreReplacementRepositoryInterface {
	mock := &MockGenreReplacementRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenreReplacementRepositoryInterface is an autogenerated mock type for the GenreReplacementRepositoryInterface type
type MockGenreReplacementRepositoryInterface struct {
	mock.Mock
}

type MockGenreReplacementRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenreReplacementRepositoryInterface) EXPECT() *MockGenreReplacementRepositoryInterface_Expecter {
	return &MockGenreReplacementRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockGenreReplacementRepositoryInterface
func (_mock *MockGenreReplacementRepositoryInterface) Create(replacement *models.GenreReplacement) error {
	ret := _mock.Called(replacement)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.GenreReplacement) error); ok {
		r0 = returnFunc(replacement)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGenreReplacementRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGenreReplacementRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - replacement *models.GenreReplacement
func (_e *MockGenreReplacementRepositoryInterface_Expecter) Create(replacement interface{}) *MockGenreReplacementRepositoryInterface_Create_Call {
	return &MockGenreReplacementRepositoryInterface_Create_Call{Call: _e.mock.On("Create", replacement)}
}

func (_c *MockGenreReplacementRepositoryInterface_Create_Call) Run(run func(replacement *models.GenreReplacement)) *MockGenreReplacementRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.GenreReplacement
		if args[0] != nil {
			arg0 = args[0].(*models.GenreReplacement)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGenreReplacementRepositoryInterface_Create_Call) Return(err error) *MockGenreReplacementRepositoryInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGenreReplacementRepositoryInterface_Create_Call) RunAndReturn(run func(replacement *models.GenreReplacement) error) *MockGenreReplacementRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockGenreReplacementRepositoryInterface
func (_mock *MockGenreReplacementRepositoryInterface) Delete(original string) error {
	ret := _mock.Called(original)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(original)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGenreReplacementRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGenreReplacementRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - original string
func (_e *MockGenreReplacementRepositoryInterface_Expecter) Delete(original interface{}) *MockGenreReplacementRepositoryInterface_Delete_Call {
	return &MockGenreReplacementRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", original)}
}

func (_c *MockGenreReplacementRepositoryInterface_Delete_Call) Run(run func(original string)) *MockGenreReplacementRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGenreReplacementRepositoryInterface_Delete_Call) Return(err error) *MockGenreReplacementRepositoryInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGenreReplacementRepositoryInterface_Delete_Call) RunAndReturn(run func(original string) error) *MockGenreReplacementRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOriginal provides a mock function for the type MockGenreReplacementRepositoryInterface
func (_mock *MockGenreReplacementRepositoryInterface) FindByOriginal(original string) (*models.GenreReplacement, error) {
	ret := _mock.Called(original)

	if len(ret) == 0 {
		panic("no return value specified for FindByOriginal")
	}

	var r0 *models.GenreReplacement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.GenreReplacement, error)); ok {
		return returnFunc(original)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.GenreReplacement); ok {
		r0 = returnFunc(original)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GenreReplacement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(original)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenreReplacementRepositoryInterface_FindByOriginal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOriginal'
type MockGenreReplacementRepositoryInterface_FindByOriginal_Call struct {
	*mock.Call
}

// FindByOriginal is a helper method to define mock.On call
//   - original string
func (_e *MockGenreReplacementRepositoryInterface_Expecter) FindByOriginal(original interface{}) *MockGenreReplacementRepositoryInterface_FindByOriginal_Call {
	return &MockGenreReplacementRepositoryInterface_FindByOriginal_Call{Call: _e.mock.On("FindByOriginal", original)}
}

func (_c *MockGenreReplacementRepositoryInterface_FindByOriginal_Call) Run(run func(original string)) *MockGenreReplacementRepositoryInterface_FindByOriginal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGenreReplacementRepositoryInterface_FindByOriginal_Call) Return(genreReplacement *models.GenreReplacement, err error) *MockGenreReplacementRepositoryInterface_FindByOriginal_Call {
	_c.Call.Return(genreReplacement, err)
	return _c
}

func (_c *MockGenreReplacementRepositoryInterface_FindByOriginal_Call) RunAndReturn(run func(original string) (*models.GenreReplacement, error)) *MockGenreReplacementRepositoryInterface_FindByOriginal_Call {
	_c.Call.Return(run)
	return _c
}

// GetReplacementMap provides a mock function for the type MockGenreReplacementRepositoryInterface
func (_mock *MockGenreReplacementRepositoryInterface) GetReplacementMap() (map[string]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetReplacementMap")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[string]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenreReplacementRepositoryInterface_GetReplacementMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReplacementMap'
type MockGenreReplacementRepositoryInterface_GetReplacementMap_Call struct {
	*mock.Call
}

// GetReplacementMap is a helper method to define mock.On call
func (_e *MockGenreReplacementRepositoryInterface_Expecter) GetReplacementMap() *MockGenreReplacementRepositoryInterface_GetReplacementMap_Call {
	return &MockGenreReplacementRepositoryInterface_GetReplacementMap_Call{Call: _e.mock.On("GetReplacementMap")}
}

func (_c *MockGenreReplacementRepositoryInterface_GetReplacementMap_Call) Run(run func()) *MockGenreReplacementRepositoryInterface_GetReplacementMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGenreReplacementRepositoryInterface_GetReplacementMap_Call) Return(stringToString map[string]string, err error) *MockGenreReplacementRepositoryInterface_GetReplacementMap_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockGenreReplacementRepositoryInterface_GetReplacementMap_Call) RunAndReturn(run func() (map[string]string, error)) *MockGenreReplacementRepositoryInterface_GetReplacementMap_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockGenreReplacementRepositoryInterface
func (_mock *MockGenreReplacementRepositoryInterface) List() ([]models.GenreReplacement, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.GenreReplacement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.GenreReplacement, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.GenreReplacement); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GenreReplacement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenreReplacementRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockGenreReplacementRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockGenreReplacementRepositoryInterface_Expecter) List() *MockGenreReplacementRepositoryInterface_List_Call {
	return &MockGenreReplacementRepositoryInterface_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockGenreReplacementRepositoryInterface_List_Call) Run(run func()) *MockGenreReplacementRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGenreReplacementRepositoryInterface_List_Call) Return(genreReplacements []models.GenreReplacement, err error) *MockGenreReplacementRepositoryInterface_List_Call {
	_c.Call.Return(genreReplacements, err)
	return _c
}

func (_c *MockGenreReplacementRepositoryInterface_List_Call) RunAndReturn(run func() ([]models.GenreReplacement, error)) *MockGenreReplacementRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockGenreReplacementRepositoryInterface
func (_mock *MockGenreReplacementRepositoryInterface) Upsert(replacement *models.GenreReplacement) error {
	ret := _mock.Called(replacement)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.GenreReplacement) error); ok {
		r0 = returnFunc(replacement)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGenreReplacementRepositoryInterface_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockGenreReplacementRepositoryInterface_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - replacement *models.GenreReplacement
func (_e *MockGenreReplacementRepositoryInterface_Expecter) Upsert(replacement interface{}) *MockGenreReplacementRepositoryInterface_Upsert_Call {
	return &MockGenreReplacementRepositoryInterface_Upsert_Call{Call: _e.mock.On("Upsert", replacement)}
}

func (_c *MockGenreReplacementRepositoryInterface_Upsert_Call) Run(run func(replacement *models.GenreReplacement)) *MockGenreReplacementRepositoryInterface_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.GenreReplacement
		if args[0] != nil {
			arg0 = args[0].(*models.GenreReplacement)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGenreReplacementRepositoryInterface_Upsert_Call) Return(err error) *MockGenreReplacementRepositoryInterface_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGenreReplacementRepositoryInterface_Upsert_Call) RunAndReturn(run func(replacement *models.GenreReplacement) error) *MockGenreReplacementRepositoryInterface_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
