// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/javinizer/javinizer-go/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHistoryRepositoryInterface creates a new instance of MockHistoryRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHistoryRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHistoryRepositoryInterface {
	mock := &MockHistoryRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHistoryRepositoryInterface is an autogenerated mock type for the HistoryRepositoryInterface type
type MockHistoryRepositoryInterface struct {
	mock.Mock
}

type MockHistoryRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHistoryRepositoryInterface) EXPECT() *MockHistoryRepositoryInterface_Expecter {
	return &MockHistoryRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockHistoryRepositoryInterface_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHistoryRepositoryInterface_Expecter) Count(ctx any) *MockHistoryRepositoryInterface_Count_Call {
	return &MockHistoryRepositoryInterface_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockHistoryRepositoryInterface_Count_Call) Run(run func(ctx context.Context)) *MockHistoryRepositoryInterface_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_Count_Call) Return(n int64, err error) *MockHistoryRepositoryInterface_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockHistoryRepositoryInterface_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountByOperation provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) CountByOperation(ctx context.Context, operation models.HistoryOperation) (int64, error) {
	ret := _mock.Called(ctx, operation)

	if len(ret) == 0 {
		panic("no return value specified for CountByOperation")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.HistoryOperation) (int64, error)); ok {
		return returnFunc(ctx, operation)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.HistoryOperation) int64); ok {
		r0 = returnFunc(ctx, operation)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.HistoryOperation) error); ok {
		r1 = returnFunc(ctx, operation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_CountByOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByOperation'
type MockHistoryRepositoryInterface_CountByOperation_Call struct {
	*mock.Call
}

// CountByOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - operation models.HistoryOperation
func (_e *MockHistoryRepositoryInterface_Expecter) CountByOperation(ctx any, operation any) *MockHistoryRepositoryInterface_CountByOperation_Call {
	return &MockHistoryRepositoryInterface_CountByOperation_Call{Call: _e.mock.On("CountByOperation", ctx, operation)}
}

func (_c *MockHistoryRepositoryInterface_CountByOperation_Call) Run(run func(ctx context.Context, operation models.HistoryOperation)) *MockHistoryRepositoryInterface_CountByOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.HistoryOperation
		if args[1] != nil {
			arg1 = args[1].(models.HistoryOperation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_CountByOperation_Call) Return(n int64, err error) *MockHistoryRepositoryInterface_CountByOperation_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_CountByOperation_Call) RunAndReturn(run func(ctx context.Context, operation models.HistoryOperation) (int64, error)) *MockHistoryRepositoryInterface_CountByOperation_Call {
	_c.Call.Return(run)
	return _c
}

// CountByStatus provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) CountByStatus(ctx context.Context, status models.HistoryStatus) (int64, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for CountByStatus")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.HistoryStatus) (int64, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.HistoryStatus) int64); ok {
		r0 = returnFunc(ctx, status)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.HistoryStatus) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_CountByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByStatus'
type MockHistoryRepositoryInterface_CountByStatus_Call struct {
	*mock.Call
}

// CountByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status models.HistoryStatus
func (_e *MockHistoryRepositoryInterface_Expecter) CountByStatus(ctx any, status any) *MockHistoryRepositoryInterface_CountByStatus_Call {
	return &MockHistoryRepositoryInterface_CountByStatus_Call{Call: _e.mock.On("CountByStatus", ctx, status)}
}

func (_c *MockHistoryRepositoryInterface_CountByStatus_Call) Run(run func(ctx context.Context, status models.HistoryStatus)) *MockHistoryRepositoryInterface_CountByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.HistoryStatus
		if args[1] != nil {
			arg1 = args[1].(models.HistoryStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_CountByStatus_Call) Return(n int64, err error) *MockHistoryRepositoryInterface_CountByStatus_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_CountByStatus_Call) RunAndReturn(run func(ctx context.Context, status models.HistoryStatus) (int64, error)) *MockHistoryRepositoryInterface_CountByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) Create(ctx context.Context, history *models.History) error {
	ret := _mock.Called(ctx, history)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.History) error); ok {
		r0 = returnFunc(ctx, history)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHistoryRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHistoryRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - history *models.History
func (_e *MockHistoryRepositoryInterface_Expecter) Create(ctx any, history any) *MockHistoryRepositoryInterface_Create_Call {
	return &MockHistoryRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, history)}
}

func (_c *MockHistoryRepositoryInterface_Create_Call) Run(run func(ctx context.Context, history *models.History)) *MockHistoryRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.History
		if args[1] != nil {
			arg1 = args[1].(*models.History)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_Create_Call) Return(err error) *MockHistoryRepositoryInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, history *models.History) error) *MockHistoryRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) Delete(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHistoryRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockHistoryRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockHistoryRepositoryInterface_Expecter) Delete(ctx any, id any) *MockHistoryRepositoryInterface_Delete_Call {
	return &MockHistoryRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockHistoryRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockHistoryRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_Delete_Call) Return(err error) *MockHistoryRepositoryInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockHistoryRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByMovieID provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) DeleteByMovieID(ctx context.Context, movieID string) error {
	ret := _mock.Called(ctx, movieID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByMovieID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, movieID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHistoryRepositoryInterface_DeleteByMovieID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByMovieID'
type MockHistoryRepositoryInterface_DeleteByMovieID_Call struct {
	*mock.Call
}

// DeleteByMovieID is a helper method to define mock.On call
//   - ctx context.Context
//   - movieID string
func (_e *MockHistoryRepositoryInterface_Expecter) DeleteByMovieID(ctx any, movieID any) *MockHistoryRepositoryInterface_DeleteByMovieID_Call {
	return &MockHistoryRepositoryInterface_DeleteByMovieID_Call{Call: _e.mock.On("DeleteByMovieID", ctx, movieID)}
}

func (_c *MockHistoryRepositoryInterface_DeleteByMovieID_Call) Run(run func(ctx context.Context, movieID string)) *MockHistoryRepositoryInterface_DeleteByMovieID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_DeleteByMovieID_Call) Return(err error) *MockHistoryRepositoryInterface_DeleteByMovieID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_DeleteByMovieID_Call) RunAndReturn(run func(ctx context.Context, movieID string) error) *MockHistoryRepositoryInterface_DeleteByMovieID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOlderThan provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) DeleteOlderThan(ctx context.Context, date time.Time) error {
	ret := _mock.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = returnFunc(ctx, date)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHistoryRepositoryInterface_DeleteOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOlderThan'
type MockHistoryRepositoryInterface_DeleteOlderThan_Call struct {
	*mock.Call
}

// DeleteOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - date time.Time
func (_e *MockHistoryRepositoryInterface_Expecter) DeleteOlderThan(ctx any, date any) *MockHistoryRepositoryInterface_DeleteOlderThan_Call {
	return &MockHistoryRepositoryInterface_DeleteOlderThan_Call{Call: _e.mock.On("DeleteOlderThan", ctx, date)}
}

func (_c *MockHistoryRepositoryInterface_DeleteOlderThan_Call) Run(run func(ctx context.Context, date time.Time)) *MockHistoryRepositoryInterface_DeleteOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_DeleteOlderThan_Call) Return(err error) *MockHistoryRepositoryInterface_DeleteOlderThan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_DeleteOlderThan_Call) RunAndReturn(run func(ctx context.Context, date time.Time) error) *MockHistoryRepositoryInterface_DeleteOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBatchJobID provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) FindByBatchJobID(ctx context.Context, batchJobID string) ([]models.History, error) {
	ret := _mock.Called(ctx, batchJobID)

	if len(ret) == 0 {
		panic("no return value specified for FindByBatchJobID")
	}

	var r0 []models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.History, error)); ok {
		return returnFunc(ctx, batchJobID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.History); ok {
		r0 = returnFunc(ctx, batchJobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, batchJobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_FindByBatchJobID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBatchJobID'
type MockHistoryRepositoryInterface_FindByBatchJobID_Call struct {
	*mock.Call
}

// FindByBatchJobID is a helper method to define mock.On call
//   - ctx context.Context
//   - batchJobID string
func (_e *MockHistoryRepositoryInterface_Expecter) FindByBatchJobID(ctx any, batchJobID any) *MockHistoryRepositoryInterface_FindByBatchJobID_Call {
	return &MockHistoryRepositoryInterface_FindByBatchJobID_Call{Call: _e.mock.On("FindByBatchJobID", ctx, batchJobID)}
}

func (_c *MockHistoryRepositoryInterface_FindByBatchJobID_Call) Run(run func(ctx context.Context, batchJobID string)) *MockHistoryRepositoryInterface_FindByBatchJobID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByBatchJobID_Call) Return(historys []models.History, err error) *MockHistoryRepositoryInterface_FindByBatchJobID_Call {
	_c.Call.Return(historys, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByBatchJobID_Call) RunAndReturn(run func(ctx context.Context, batchJobID string) ([]models.History, error)) *MockHistoryRepositoryInterface_FindByBatchJobID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByDateRange provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) FindByDateRange(ctx context.Context, start time.Time, end time.Time) ([]models.History, error) {
	ret := _mock.Called(ctx, start, end)

	if len(ret) == 0 {
		panic("no return value specified for FindByDateRange")
	}

	var r0 []models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]models.History, error)); ok {
		return returnFunc(ctx, start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []models.History); ok {
		r0 = returnFunc(ctx, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, start, end)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_FindByDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByDateRange'
type MockHistoryRepositoryInterface_FindByDateRange_Call struct {
	*mock.Call
}

// FindByDateRange is a helper method to define mock.On call
//   - ctx context.Context
//   - start time.Time
//   - end time.Time
func (_e *MockHistoryRepositoryInterface_Expecter) FindByDateRange(ctx any, start any, end any) *MockHistoryRepositoryInterface_FindByDateRange_Call {
	return &MockHistoryRepositoryInterface_FindByDateRange_Call{Call: _e.mock.On("FindByDateRange", ctx, start, end)}
}

func (_c *MockHistoryRepositoryInterface_FindByDateRange_Call) Run(run func(ctx context.Context, start time.Time, end time.Time)) *MockHistoryRepositoryInterface_FindByDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByDateRange_Call) Return(historys []models.History, err error) *MockHistoryRepositoryInterface_FindByDateRange_Call {
	_c.Call.Return(historys, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByDateRange_Call) RunAndReturn(run func(ctx context.Context, start time.Time, end time.Time) ([]models.History, error)) *MockHistoryRepositoryInterface_FindByDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) FindByID(ctx context.Context, id uint) (*models.History, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*models.History, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *models.History); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockHistoryRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockHistoryRepositoryInterface_Expecter) FindByID(ctx any, id any) *MockHistoryRepositoryInterface_FindByID_Call {
	return &MockHistoryRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockHistoryRepositoryInterface_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockHistoryRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByID_Call) Return(history *models.History, err error) *MockHistoryRepositoryInterface_FindByID_Call {
	_c.Call.Return(history, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uint) (*models.History, error)) *MockHistoryRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByMovieID provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) FindByMovieID(ctx context.Context, movieID string) ([]models.History, error) {
	ret := _mock.Called(ctx, movieID)

	if len(ret) == 0 {
		panic("no return value specified for FindByMovieID")
	}

	var r0 []models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.History, error)); ok {
		return returnFunc(ctx, movieID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.History); ok {
		r0 = returnFunc(ctx, movieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, movieID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_FindByMovieID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByMovieID'
type MockHistoryRepositoryInterface_FindByMovieID_Call struct {
	*mock.Call
}

// FindByMovieID is a helper method to define mock.On call
//   - ctx context.Context
//   - movieID string
func (_e *MockHistoryRepositoryInterface_Expecter) FindByMovieID(ctx any, movieID any) *MockHistoryRepositoryInterface_FindByMovieID_Call {
	return &MockHistoryRepositoryInterface_FindByMovieID_Call{Call: _e.mock.On("FindByMovieID", ctx, movieID)}
}

func (_c *MockHistoryRepositoryInterface_FindByMovieID_Call) Run(run func(ctx context.Context, movieID string)) *MockHistoryRepositoryInterface_FindByMovieID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByMovieID_Call) Return(historys []models.History, err error) *MockHistoryRepositoryInterface_FindByMovieID_Call {
	_c.Call.Return(historys, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByMovieID_Call) RunAndReturn(run func(ctx context.Context, movieID string) ([]models.History, error)) *MockHistoryRepositoryInterface_FindByMovieID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOperation provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) FindByOperation(ctx context.Context, operation models.HistoryOperation, limit int) ([]models.History, error) {
	ret := _mock.Called(ctx, operation, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByOperation")
	}

	var r0 []models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.HistoryOperation, int) ([]models.History, error)); ok {
		return returnFunc(ctx, operation, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.HistoryOperation, int) []models.History); ok {
		r0 = returnFunc(ctx, operation, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.HistoryOperation, int) error); ok {
		r1 = returnFunc(ctx, operation, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_FindByOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOperation'
type MockHistoryRepositoryInterface_FindByOperation_Call struct {
	*mock.Call
}

// FindByOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - operation models.HistoryOperation
//   - limit int
func (_e *MockHistoryRepositoryInterface_Expecter) FindByOperation(ctx any, operation any, limit any) *MockHistoryRepositoryInterface_FindByOperation_Call {
	return &MockHistoryRepositoryInterface_FindByOperation_Call{Call: _e.mock.On("FindByOperation", ctx, operation, limit)}
}

func (_c *MockHistoryRepositoryInterface_FindByOperation_Call) Run(run func(ctx context.Context, operation models.HistoryOperation, limit int)) *MockHistoryRepositoryInterface_FindByOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.HistoryOperation
		if args[1] != nil {
			arg1 = args[1].(models.HistoryOperation)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByOperation_Call) Return(historys []models.History, err error) *MockHistoryRepositoryInterface_FindByOperation_Call {
	_c.Call.Return(historys, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByOperation_Call) RunAndReturn(run func(ctx context.Context, operation models.HistoryOperation, limit int) ([]models.History, error)) *MockHistoryRepositoryInterface_FindByOperation_Call {
	_c.Call.Return(run)
	return _c
}

// FindByStatus provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) FindByStatus(ctx context.Context, status models.HistoryStatus, limit int) ([]models.History, error) {
	ret := _mock.Called(ctx, status, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByStatus")
	}

	var r0 []models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.HistoryStatus, int) ([]models.History, error)); ok {
		return returnFunc(ctx, status, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.HistoryStatus, int) []models.History); ok {
		r0 = returnFunc(ctx, status, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.HistoryStatus, int) error); ok {
		r1 = returnFunc(ctx, status, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_FindByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByStatus'
type MockHistoryRepositoryInterface_FindByStatus_Call struct {
	*mock.Call
}

// FindByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status models.HistoryStatus
//   - limit int
func (_e *MockHistoryRepositoryInterface_Expecter) FindByStatus(ctx any, status any, limit any) *MockHistoryRepositoryInterface_FindByStatus_Call {
	return &MockHistoryRepositoryInterface_FindByStatus_Call{Call: _e.mock.On("FindByStatus", ctx, status, limit)}
}

func (_c *MockHistoryRepositoryInterface_FindByStatus_Call) Run(run func(ctx context.Context, status models.HistoryStatus, limit int)) *MockHistoryRepositoryInterface_FindByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.HistoryStatus
		if args[1] != nil {
			arg1 = args[1].(models.HistoryStatus)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByStatus_Call) Return(historys []models.History, err error) *MockHistoryRepositoryInterface_FindByStatus_Call {
	_c.Call.Return(historys, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByStatus_Call) RunAndReturn(run func(ctx context.Context, status models.HistoryStatus, limit int) ([]models.History, error)) *MockHistoryRepositoryInterface_FindByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// FindRecent provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) FindRecent(ctx context.Context, limit int) ([]models.History, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindRecent")
	}

	var r0 []models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.History, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.History); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_FindRecent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRecent'
type MockHistoryRepositoryInterface_FindRecent_Call struct {
	*mock.Call
}

// FindRecent is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockHistoryRepositoryInterface_Expecter) FindRecent(ctx any, limit any) *MockHistoryRepositoryInterface_FindRecent_Call {
	return &MockHistoryRepositoryInterface_FindRecent_Call{Call: _e.mock.On("FindRecent", ctx, limit)}
}

func (_c *MockHistoryRepositoryInterface_FindRecent_Call) Run(run func(ctx context.Context, limit int)) *MockHistoryRepositoryInterface_FindRecent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindRecent_Call) Return(historys []models.History, err error) *MockHistoryRepositoryInterface_FindRecent_Call {
	_c.Call.Return(historys, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindRecent_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]models.History, error)) *MockHistoryRepositoryInterface_FindRecent_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) List(ctx context.Context, limit int, offset int) ([]models.History, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]models.History, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []models.History); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockHistoryRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockHistoryRepositoryInterface_Expecter) List(ctx any, limit any, offset any) *MockHistoryRepositoryInterface_List_Call {
	return &MockHistoryRepositoryInterface_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockHistoryRepositoryInterface_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockHistoryRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_List_Call) Return(historys []models.History, err error) *MockHistoryRepositoryInterface_List_Call {
	_c.Call.Return(historys, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]models.History, error)) *MockHistoryRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}
