// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/javinizer/javinizer-go/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHistoryRepositoryInterface creates a new instance of MockHistoryRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHistoryRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHistoryRepositoryInterface {
	mock := &MockHistoryRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHistoryRepositoryInterface is an autogenerated mock type for the HistoryRepositoryInterface type
type MockHistoryRepositoryInterface struct {
	mock.Mock
}

type MockHistoryRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHistoryRepositoryInterface) EXPECT() *MockHistoryRepositoryInterface_Expecter {
	return &MockHistoryRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) Count() (int64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockHistoryRepositoryInterface_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
func (_e *MockHistoryRepositoryInterface_Expecter) Count() *MockHistoryRepositoryInterface_Count_Call {
	return &MockHistoryRepositoryInterface_Count_Call{Call: _e.mock.On("Count")}
}

func (_c *MockHistoryRepositoryInterface_Count_Call) Run(run func()) *MockHistoryRepositoryInterface_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_Count_Call) Return(n int64, err error) *MockHistoryRepositoryInterface_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_Count_Call) RunAndReturn(run func() (int64, error)) *MockHistoryRepositoryInterface_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountByOperation provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) CountByOperation(operation string) (int64, error) {
	ret := _mock.Called(operation)

	if len(ret) == 0 {
		panic("no return value specified for CountByOperation")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return returnFunc(operation)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int64); ok {
		r0 = returnFunc(operation)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(operation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_CountByOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByOperation'
type MockHistoryRepositoryInterface_CountByOperation_Call struct {
	*mock.Call
}

// CountByOperation is a helper method to define mock.On call
//   - operation string
func (_e *MockHistoryRepositoryInterface_Expecter) CountByOperation(operation interface{}) *MockHistoryRepositoryInterface_CountByOperation_Call {
	return &MockHistoryRepositoryInterface_CountByOperation_Call{Call: _e.mock.On("CountByOperation", operation)}
}

func (_c *MockHistoryRepositoryInterface_CountByOperation_Call) Run(run func(operation string)) *MockHistoryRepositoryInterface_CountByOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_CountByOperation_Call) Return(n int64, err error) *MockHistoryRepositoryInterface_CountByOperation_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_CountByOperation_Call) RunAndReturn(run func(operation string) (int64, error)) *MockHistoryRepositoryInterface_CountByOperation_Call {
	_c.Call.Return(run)
	return _c
}

// CountByStatus provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) CountByStatus(status string) (int64, error) {
	ret := _mock.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for CountByStatus")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return returnFunc(status)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int64); ok {
		r0 = returnFunc(status)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_CountByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByStatus'
type MockHistoryRepositoryInterface_CountByStatus_Call struct {
	*mock.Call
}

// CountByStatus is a helper method to define mock.On call
//   - status string
func (_e *MockHistoryRepositoryInterface_Expecter) CountByStatus(status interface{}) *MockHistoryRepositoryInterface_CountByStatus_Call {
	return &MockHistoryRepositoryInterface_CountByStatus_Call{Call: _e.mock.On("CountByStatus", status)}
}

func (_c *MockHistoryRepositoryInterface_CountByStatus_Call) Run(run func(status string)) *MockHistoryRepositoryInterface_CountByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_CountByStatus_Call) Return(n int64, err error) *MockHistoryRepositoryInterface_CountByStatus_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_CountByStatus_Call) RunAndReturn(run func(status string) (int64, error)) *MockHistoryRepositoryInterface_CountByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) Create(history *models.History) error {
	ret := _mock.Called(history)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.History) error); ok {
		r0 = returnFunc(history)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHistoryRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHistoryRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - history *models.History
func (_e *MockHistoryRepositoryInterface_Expecter) Create(history interface{}) *MockHistoryRepositoryInterface_Create_Call {
	return &MockHistoryRepositoryInterface_Create_Call{Call: _e.mock.On("Create", history)}
}

func (_c *MockHistoryRepositoryInterface_Create_Call) Run(run func(history *models.History)) *MockHistoryRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.History
		if args[0] != nil {
			arg0 = args[0].(*models.History)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_Create_Call) Return(err error) *MockHistoryRepositoryInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_Create_Call) RunAndReturn(run func(history *models.History) error) *MockHistoryRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) Delete(id uint) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHistoryRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockHistoryRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockHistoryRepositoryInterface_Expecter) Delete(id interface{}) *MockHistoryRepositoryInterface_Delete_Call {
	return &MockHistoryRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockHistoryRepositoryInterface_Delete_Call) Run(run func(id uint)) *MockHistoryRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_Delete_Call) Return(err error) *MockHistoryRepositoryInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_Delete_Call) RunAndReturn(run func(id uint) error) *MockHistoryRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByMovieID provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) DeleteByMovieID(movieID string) error {
	ret := _mock.Called(movieID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByMovieID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(movieID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHistoryRepositoryInterface_DeleteByMovieID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByMovieID'
type MockHistoryRepositoryInterface_DeleteByMovieID_Call struct {
	*mock.Call
}

// DeleteByMovieID is a helper method to define mock.On call
//   - movieID string
func (_e *MockHistoryRepositoryInterface_Expecter) DeleteByMovieID(movieID interface{}) *MockHistoryRepositoryInterface_DeleteByMovieID_Call {
	return &MockHistoryRepositoryInterface_DeleteByMovieID_Call{Call: _e.mock.On("DeleteByMovieID", movieID)}
}

func (_c *MockHistoryRepositoryInterface_DeleteByMovieID_Call) Run(run func(movieID string)) *MockHistoryRepositoryInterface_DeleteByMovieID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_DeleteByMovieID_Call) Return(err error) *MockHistoryRepositoryInterface_DeleteByMovieID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_DeleteByMovieID_Call) RunAndReturn(run func(movieID string) error) *MockHistoryRepositoryInterface_DeleteByMovieID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOlderThan provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) DeleteOlderThan(date time.Time) error {
	ret := _mock.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = returnFunc(date)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHistoryRepositoryInterface_DeleteOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOlderThan'
type MockHistoryRepositoryInterface_DeleteOlderThan_Call struct {
	*mock.Call
}

// DeleteOlderThan is a helper method to define mock.On call
//   - date time.Time
func (_e *MockHistoryRepositoryInterface_Expecter) DeleteOlderThan(date interface{}) *MockHistoryRepositoryInterface_DeleteOlderThan_Call {
	return &MockHistoryRepositoryInterface_DeleteOlderThan_Call{Call: _e.mock.On("DeleteOlderThan", date)}
}

func (_c *MockHistoryRepositoryInterface_DeleteOlderThan_Call) Run(run func(date time.Time)) *MockHistoryRepositoryInterface_DeleteOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_DeleteOlderThan_Call) Return(err error) *MockHistoryRepositoryInterface_DeleteOlderThan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_DeleteOlderThan_Call) RunAndReturn(run func(date time.Time) error) *MockHistoryRepositoryInterface_DeleteOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBatchJobID provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) FindByBatchJobID(batchJobID string) ([]models.History, error) {
	ret := _mock.Called(batchJobID)

	if len(ret) == 0 {
		panic("no return value specified for FindByBatchJobID")
	}

	var r0 []models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]models.History, error)); ok {
		return returnFunc(batchJobID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []models.History); ok {
		r0 = returnFunc(batchJobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(batchJobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_FindByBatchJobID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBatchJobID'
type MockHistoryRepositoryInterface_FindByBatchJobID_Call struct {
	*mock.Call
}

// FindByBatchJobID is a helper method to define mock.On call
//   - batchJobID string
func (_e *MockHistoryRepositoryInterface_Expecter) FindByBatchJobID(batchJobID interface{}) *MockHistoryRepositoryInterface_FindByBatchJobID_Call {
	return &MockHistoryRepositoryInterface_FindByBatchJobID_Call{Call: _e.mock.On("FindByBatchJobID", batchJobID)}
}

func (_c *MockHistoryRepositoryInterface_FindByBatchJobID_Call) Run(run func(batchJobID string)) *MockHistoryRepositoryInterface_FindByBatchJobID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByBatchJobID_Call) Return(historys []models.History, err error) *MockHistoryRepositoryInterface_FindByBatchJobID_Call {
	_c.Call.Return(historys, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByBatchJobID_Call) RunAndReturn(run func(batchJobID string) ([]models.History, error)) *MockHistoryRepositoryInterface_FindByBatchJobID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByDateRange provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) FindByDateRange(start time.Time, end time.Time) ([]models.History, error) {
	ret := _mock.Called(start, end)

	if len(ret) == 0 {
		panic("no return value specified for FindByDateRange")
	}

	var r0 []models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time, time.Time) ([]models.History, error)); ok {
		return returnFunc(start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time, time.Time) []models.History); ok {
		r0 = returnFunc(start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = returnFunc(start, end)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_FindByDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByDateRange'
type MockHistoryRepositoryInterface_FindByDateRange_Call struct {
	*mock.Call
}

// FindByDateRange is a helper method to define mock.On call
//   - start time.Time
//   - end time.Time
func (_e *MockHistoryRepositoryInterface_Expecter) FindByDateRange(start interface{}, end interface{}) *MockHistoryRepositoryInterface_FindByDateRange_Call {
	return &MockHistoryRepositoryInterface_FindByDateRange_Call{Call: _e.mock.On("FindByDateRange", start, end)}
}

func (_c *MockHistoryRepositoryInterface_FindByDateRange_Call) Run(run func(start time.Time, end time.Time)) *MockHistoryRepositoryInterface_FindByDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByDateRange_Call) Return(historys []models.History, err error) *MockHistoryRepositoryInterface_FindByDateRange_Call {
	_c.Call.Return(historys, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByDateRange_Call) RunAndReturn(run func(start time.Time, end time.Time) ([]models.History, error)) *MockHistoryRepositoryInterface_FindByDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) FindByID(id uint) (*models.History, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*models.History, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *models.History); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockHistoryRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint
func (_e *MockHistoryRepositoryInterface_Expecter) FindByID(id interface{}) *MockHistoryRepositoryInterface_FindByID_Call {
	return &MockHistoryRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockHistoryRepositoryInterface_FindByID_Call) Run(run func(id uint)) *MockHistoryRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByID_Call) Return(history *models.History, err error) *MockHistoryRepositoryInterface_FindByID_Call {
	_c.Call.Return(history, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByID_Call) RunAndReturn(run func(id uint) (*models.History, error)) *MockHistoryRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByMovieID provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) FindByMovieID(movieID string) ([]models.History, error) {
	ret := _mock.Called(movieID)

	if len(ret) == 0 {
		panic("no return value specified for FindByMovieID")
	}

	var r0 []models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]models.History, error)); ok {
		return returnFunc(movieID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []models.History); ok {
		r0 = returnFunc(movieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(movieID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_FindByMovieID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByMovieID'
type MockHistoryRepositoryInterface_FindByMovieID_Call struct {
	*mock.Call
}

// FindByMovieID is a helper method to define mock.On call
//   - movieID string
func (_e *MockHistoryRepositoryInterface_Expecter) FindByMovieID(movieID interface{}) *MockHistoryRepositoryInterface_FindByMovieID_Call {
	return &MockHistoryRepositoryInterface_FindByMovieID_Call{Call: _e.mock.On("FindByMovieID", movieID)}
}

func (_c *MockHistoryRepositoryInterface_FindByMovieID_Call) Run(run func(movieID string)) *MockHistoryRepositoryInterface_FindByMovieID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByMovieID_Call) Return(historys []models.History, err error) *MockHistoryRepositoryInterface_FindByMovieID_Call {
	_c.Call.Return(historys, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByMovieID_Call) RunAndReturn(run func(movieID string) ([]models.History, error)) *MockHistoryRepositoryInterface_FindByMovieID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOperation provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) FindByOperation(operation string, limit int) ([]models.History, error) {
	ret := _mock.Called(operation, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByOperation")
	}

	var r0 []models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int) ([]models.History, error)); ok {
		return returnFunc(operation, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) []models.History); ok {
		r0 = returnFunc(operation, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = returnFunc(operation, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_FindByOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOperation'
type MockHistoryRepositoryInterface_FindByOperation_Call struct {
	*mock.Call
}

// FindByOperation is a helper method to define mock.On call
//   - operation string
//   - limit int
func (_e *MockHistoryRepositoryInterface_Expecter) FindByOperation(operation interface{}, limit interface{}) *MockHistoryRepositoryInterface_FindByOperation_Call {
	return &MockHistoryRepositoryInterface_FindByOperation_Call{Call: _e.mock.On("FindByOperation", operation, limit)}
}

func (_c *MockHistoryRepositoryInterface_FindByOperation_Call) Run(run func(operation string, limit int)) *MockHistoryRepositoryInterface_FindByOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByOperation_Call) Return(historys []models.History, err error) *MockHistoryRepositoryInterface_FindByOperation_Call {
	_c.Call.Return(historys, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByOperation_Call) RunAndReturn(run func(operation string, limit int) ([]models.History, error)) *MockHistoryRepositoryInterface_FindByOperation_Call {
	_c.Call.Return(run)
	return _c
}

// FindByStatus provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) FindByStatus(status string, limit int) ([]models.History, error) {
	ret := _mock.Called(status, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByStatus")
	}

	var r0 []models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int) ([]models.History, error)); ok {
		return returnFunc(status, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) []models.History); ok {
		r0 = returnFunc(status, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = returnFunc(status, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_FindByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByStatus'
type MockHistoryRepositoryInterface_FindByStatus_Call struct {
	*mock.Call
}

// FindByStatus is a helper method to define mock.On call
//   - status string
//   - limit int
func (_e *MockHistoryRepositoryInterface_Expecter) FindByStatus(status interface{}, limit interface{}) *MockHistoryRepositoryInterface_FindByStatus_Call {
	return &MockHistoryRepositoryInterface_FindByStatus_Call{Call: _e.mock.On("FindByStatus", status, limit)}
}

func (_c *MockHistoryRepositoryInterface_FindByStatus_Call) Run(run func(status string, limit int)) *MockHistoryRepositoryInterface_FindByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByStatus_Call) Return(historys []models.History, err error) *MockHistoryRepositoryInterface_FindByStatus_Call {
	_c.Call.Return(historys, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindByStatus_Call) RunAndReturn(run func(status string, limit int) ([]models.History, error)) *MockHistoryRepositoryInterface_FindByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// FindRecent provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) FindRecent(limit int) ([]models.History, error) {
	ret := _mock.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for FindRecent")
	}

	var r0 []models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]models.History, error)); ok {
		return returnFunc(limit)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []models.History); ok {
		r0 = returnFunc(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_FindRecent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRecent'
type MockHistoryRepositoryInterface_FindRecent_Call struct {
	*mock.Call
}

// FindRecent is a helper method to define mock.On call
//   - limit int
func (_e *MockHistoryRepositoryInterface_Expecter) FindRecent(limit interface{}) *MockHistoryRepositoryInterface_FindRecent_Call {
	return &MockHistoryRepositoryInterface_FindRecent_Call{Call: _e.mock.On("FindRecent", limit)}
}

func (_c *MockHistoryRepositoryInterface_FindRecent_Call) Run(run func(limit int)) *MockHistoryRepositoryInterface_FindRecent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindRecent_Call) Return(historys []models.History, err error) *MockHistoryRepositoryInterface_FindRecent_Call {
	_c.Call.Return(historys, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_FindRecent_Call) RunAndReturn(run func(limit int) ([]models.History, error)) *MockHistoryRepositoryInterface_FindRecent_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockHistoryRepositoryInterface
func (_mock *MockHistoryRepositoryInterface) List(limit int, offset int) ([]models.History, error) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.History
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]models.History, error)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []models.History); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.History)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockHistoryRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockHistoryRepositoryInterface_Expecter) List(limit interface{}, offset interface{}) *MockHistoryRepositoryInterface_List_Call {
	return &MockHistoryRepositoryInterface_List_Call{Call: _e.mock.On("List", limit, offset)}
}

func (_c *MockHistoryRepositoryInterface_List_Call) Run(run func(limit int, offset int)) *MockHistoryRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHistoryRepositoryInterface_List_Call) Return(historys []models.History, err error) *MockHistoryRepositoryInterface_List_Call {
	_c.Call.Return(historys, err)
	return _c
}

func (_c *MockHistoryRepositoryInterface_List_Call) RunAndReturn(run func(limit int, offset int) ([]models.History, error)) *MockHistoryRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}
