// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/javinizer/javinizer-go/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMovieRepositoryInterface creates a new instance of MockMovieRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMovieRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMovieRepositoryInterface {
	mock := &MockMovieRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMovieRepositoryInterface is an autogenerated mock type for the MovieRepositoryInterface type
type MockMovieRepositoryInterface struct {
	mock.Mock
}

type MockMovieRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMovieRepositoryInterface) EXPECT() *MockMovieRepositoryInterface_Expecter {
	return &MockMovieRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockMovieRepositoryInterface
func (_mock *MockMovieRepositoryInterface) Create(ctx context.Context, movie *models.Movie) error {
	ret := _mock.Called(ctx, movie)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Movie) error); ok {
		r0 = returnFunc(ctx, movie)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMovieRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMovieRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - movie *models.Movie
func (_e *MockMovieRepositoryInterface_Expecter) Create(ctx any, movie any) *MockMovieRepositoryInterface_Create_Call {
	return &MockMovieRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, movie)}
}

func (_c *MockMovieRepositoryInterface_Create_Call) Run(run func(ctx context.Context, movie *models.Movie)) *MockMovieRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Movie
		if args[1] != nil {
			arg1 = args[1].(*models.Movie)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMovieRepositoryInterface_Create_Call) Return(err error) *MockMovieRepositoryInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMovieRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, movie *models.Movie) error) *MockMovieRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockMovieRepositoryInterface
func (_mock *MockMovieRepositoryInterface) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMovieRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMovieRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMovieRepositoryInterface_Expecter) Delete(ctx any, id any) *MockMovieRepositoryInterface_Delete_Call {
	return &MockMovieRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockMovieRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, id string)) *MockMovieRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMovieRepositoryInterface_Delete_Call) Return(err error) *MockMovieRepositoryInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMovieRepositoryInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockMovieRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByContentID provides a mock function for the type MockMovieRepositoryInterface
func (_mock *MockMovieRepositoryInterface) FindByContentID(ctx context.Context, contentID string) (*models.Movie, error) {
	ret := _mock.Called(ctx, contentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByContentID")
	}

	var r0 *models.Movie
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Movie, error)); ok {
		return returnFunc(ctx, contentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Movie); ok {
		r0 = returnFunc(ctx, contentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Movie)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, contentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMovieRepositoryInterface_FindByContentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByContentID'
type MockMovieRepositoryInterface_FindByContentID_Call struct {
	*mock.Call
}

// FindByContentID is a helper method to define mock.On call
//   - ctx context.Context
//   - contentID string
func (_e *MockMovieRepositoryInterface_Expecter) FindByContentID(ctx any, contentID any) *MockMovieRepositoryInterface_FindByContentID_Call {
	return &MockMovieRepositoryInterface_FindByContentID_Call{Call: _e.mock.On("FindByContentID", ctx, contentID)}
}

func (_c *MockMovieRepositoryInterface_FindByContentID_Call) Run(run func(ctx context.Context, contentID string)) *MockMovieRepositoryInterface_FindByContentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMovieRepositoryInterface_FindByContentID_Call) Return(movie *models.Movie, err error) *MockMovieRepositoryInterface_FindByContentID_Call {
	_c.Call.Return(movie, err)
	return _c
}

func (_c *MockMovieRepositoryInterface_FindByContentID_Call) RunAndReturn(run func(ctx context.Context, contentID string) (*models.Movie, error)) *MockMovieRepositoryInterface_FindByContentID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockMovieRepositoryInterface
func (_mock *MockMovieRepositoryInterface) FindByID(ctx context.Context, id string) (*models.Movie, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Movie
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Movie, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Movie); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Movie)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMovieRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockMovieRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMovieRepositoryInterface_Expecter) FindByID(ctx any, id any) *MockMovieRepositoryInterface_FindByID_Call {
	return &MockMovieRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockMovieRepositoryInterface_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockMovieRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMovieRepositoryInterface_FindByID_Call) Return(movie *models.Movie, err error) *MockMovieRepositoryInterface_FindByID_Call {
	_c.Call.Return(movie, err)
	return _c
}

func (_c *MockMovieRepositoryInterface_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.Movie, error)) *MockMovieRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockMovieRepositoryInterface
func (_mock *MockMovieRepositoryInterface) List(ctx context.Context, limit int, offset int) ([]models.Movie, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Movie
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]models.Movie, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []models.Movie); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Movie)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMovieRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMovieRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockMovieRepositoryInterface_Expecter) List(ctx any, limit any, offset any) *MockMovieRepositoryInterface_List_Call {
	return &MockMovieRepositoryInterface_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockMovieRepositoryInterface_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockMovieRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMovieRepositoryInterface_List_Call) Return(movies []models.Movie, err error) *MockMovieRepositoryInterface_List_Call {
	_c.Call.Return(movies, err)
	return _c
}

func (_c *MockMovieRepositoryInterface_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]models.Movie, error)) *MockMovieRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockMovieRepositoryInterface
func (_mock *MockMovieRepositoryInterface) Update(ctx context.Context, movie *models.Movie) error {
	ret := _mock.Called(ctx, movie)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Movie) error); ok {
		r0 = returnFunc(ctx, movie)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMovieRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMovieRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - movie *models.Movie
func (_e *MockMovieRepositoryInterface_Expecter) Update(ctx any, movie any) *MockMovieRepositoryInterface_Update_Call {
	return &MockMovieRepositoryInterface_Update_Call{Call: _e.mock.On("Update", ctx, movie)}
}

func (_c *MockMovieRepositoryInterface_Update_Call) Run(run func(ctx context.Context, movie *models.Movie)) *MockMovieRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Movie
		if args[1] != nil {
			arg1 = args[1].(*models.Movie)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMovieRepositoryInterface_Update_Call) Return(err error) *MockMovieRepositoryInterface_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMovieRepositoryInterface_Update_Call) RunAndReturn(run func(ctx context.Context, movie *models.Movie) error) *MockMovieRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockMovieRepositoryInterface
func (_mock *MockMovieRepositoryInterface) Upsert(ctx context.Context, movie *models.Movie) (*models.Movie, error) {
	ret := _mock.Called(ctx, movie)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 *models.Movie
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Movie) (*models.Movie, error)); ok {
		return returnFunc(ctx, movie)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Movie) *models.Movie); ok {
		r0 = returnFunc(ctx, movie)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Movie)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Movie) error); ok {
		r1 = returnFunc(ctx, movie)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMovieRepositoryInterface_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockMovieRepositoryInterface_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - movie *models.Movie
func (_e *MockMovieRepositoryInterface_Expecter) Upsert(ctx any, movie any) *MockMovieRepositoryInterface_Upsert_Call {
	return &MockMovieRepositoryInterface_Upsert_Call{Call: _e.mock.On("Upsert", ctx, movie)}
}

func (_c *MockMovieRepositoryInterface_Upsert_Call) Run(run func(ctx context.Context, movie *models.Movie)) *MockMovieRepositoryInterface_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Movie
		if args[1] != nil {
			arg1 = args[1].(*models.Movie)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMovieRepositoryInterface_Upsert_Call) Return(movie1 *models.Movie, err error) *MockMovieRepositoryInterface_Upsert_Call {
	_c.Call.Return(movie1, err)
	return _c
}

func (_c *MockMovieRepositoryInterface_Upsert_Call) RunAndReturn(run func(ctx context.Context, movie *models.Movie) (*models.Movie, error)) *MockMovieRepositoryInterface_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertWithTranslations provides a mock function for the type MockMovieRepositoryInterface
func (_mock *MockMovieRepositoryInterface) UpsertWithTranslations(ctx context.Context, movie *models.Movie, genreTranslations []models.GenreTranslationData, actressTranslations []models.ActressTranslationData) (*models.Movie, error) {
	ret := _mock.Called(ctx, movie, genreTranslations, actressTranslations)

	if len(ret) == 0 {
		panic("no return value specified for UpsertWithTranslations")
	}

	var r0 *models.Movie
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Movie, []models.GenreTranslationData, []models.ActressTranslationData) (*models.Movie, error)); ok {
		return returnFunc(ctx, movie, genreTranslations, actressTranslations)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Movie, []models.GenreTranslationData, []models.ActressTranslationData) *models.Movie); ok {
		r0 = returnFunc(ctx, movie, genreTranslations, actressTranslations)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Movie)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Movie, []models.GenreTranslationData, []models.ActressTranslationData) error); ok {
		r1 = returnFunc(ctx, movie, genreTranslations, actressTranslations)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMovieRepositoryInterface_UpsertWithTranslations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertWithTranslations'
type MockMovieRepositoryInterface_UpsertWithTranslations_Call struct {
	*mock.Call
}

// UpsertWithTranslations is a helper method to define mock.On call
//   - ctx context.Context
//   - movie *models.Movie
//   - genreTranslations []models.GenreTranslationData
//   - actressTranslations []models.ActressTranslationData
func (_e *MockMovieRepositoryInterface_Expecter) UpsertWithTranslations(ctx any, movie any, genreTranslations any, actressTranslations any) *MockMovieRepositoryInterface_UpsertWithTranslations_Call {
	return &MockMovieRepositoryInterface_UpsertWithTranslations_Call{Call: _e.mock.On("UpsertWithTranslations", ctx, movie, genreTranslations, actressTranslations)}
}

func (_c *MockMovieRepositoryInterface_UpsertWithTranslations_Call) Run(run func(ctx context.Context, movie *models.Movie, genreTranslations []models.GenreTranslationData, actressTranslations []models.ActressTranslationData)) *MockMovieRepositoryInterface_UpsertWithTranslations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Movie
		if args[1] != nil {
			arg1 = args[1].(*models.Movie)
		}
		var arg2 []models.GenreTranslationData
		if args[2] != nil {
			arg2 = args[2].([]models.GenreTranslationData)
		}
		var arg3 []models.ActressTranslationData
		if args[3] != nil {
			arg3 = args[3].([]models.ActressTranslationData)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMovieRepositoryInterface_UpsertWithTranslations_Call) Return(movie1 *models.Movie, err error) *MockMovieRepositoryInterface_UpsertWithTranslations_Call {
	_c.Call.Return(movie1, err)
	return _c
}

func (_c *MockMovieRepositoryInterface_UpsertWithTranslations_Call) RunAndReturn(run func(ctx context.Context, movie *models.Movie, genreTranslations []models.GenreTranslationData, actressTranslations []models.ActressTranslationData) (*models.Movie, error)) *MockMovieRepositoryInterface_UpsertWithTranslations_Call {
	_c.Call.Return(run)
	return _c
}
