// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/javinizer/javinizer-go/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWordReplacementRepositoryInterface creates a new instance of MockWordReplacementRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWordReplacementRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWordReplacementRepositoryInterface {
	mock := &MockWordReplacementRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWordReplacementRepositoryInterface is an autogenerated mock type for the WordReplacementRepositoryInterface type
type MockWordReplacementRepositoryInterface struct {
	mock.Mock
}

type MockWordReplacementRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWordReplacementRepositoryInterface) EXPECT() *MockWordReplacementRepositoryInterface_Expecter {
	return &MockWordReplacementRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockWordReplacementRepositoryInterface
func (_mock *MockWordReplacementRepositoryInterface) Create(ctx context.Context, replacement *models.WordReplacement) error {
	ret := _mock.Called(ctx, replacement)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.WordReplacement) error); ok {
		r0 = returnFunc(ctx, replacement)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWordReplacementRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWordReplacementRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - replacement *models.WordReplacement
func (_e *MockWordReplacementRepositoryInterface_Expecter) Create(ctx any, replacement any) *MockWordReplacementRepositoryInterface_Create_Call {
	return &MockWordReplacementRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, replacement)}
}

func (_c *MockWordReplacementRepositoryInterface_Create_Call) Run(run func(ctx context.Context, replacement *models.WordReplacement)) *MockWordReplacementRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.WordReplacement
		if args[1] != nil {
			arg1 = args[1].(*models.WordReplacement)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_Create_Call) Return(err error) *MockWordReplacementRepositoryInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, replacement *models.WordReplacement) error) *MockWordReplacementRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockWordReplacementRepositoryInterface
func (_mock *MockWordReplacementRepositoryInterface) Delete(ctx context.Context, original string) error {
	ret := _mock.Called(ctx, original)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, original)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWordReplacementRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWordReplacementRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - original string
func (_e *MockWordReplacementRepositoryInterface_Expecter) Delete(ctx any, original any) *MockWordReplacementRepositoryInterface_Delete_Call {
	return &MockWordReplacementRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, original)}
}

func (_c *MockWordReplacementRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, original string)) *MockWordReplacementRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_Delete_Call) Return(err error) *MockWordReplacementRepositoryInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, original string) error) *MockWordReplacementRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockWordReplacementRepositoryInterface
func (_mock *MockWordReplacementRepositoryInterface) DeleteByID(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWordReplacementRepositoryInterface_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockWordReplacementRepositoryInterface_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockWordReplacementRepositoryInterface_Expecter) DeleteByID(ctx any, id any) *MockWordReplacementRepositoryInterface_DeleteByID_Call {
	return &MockWordReplacementRepositoryInterface_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockWordReplacementRepositoryInterface_DeleteByID_Call) Run(run func(ctx context.Context, id uint)) *MockWordReplacementRepositoryInterface_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_DeleteByID_Call) Return(err error) *MockWordReplacementRepositoryInterface_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockWordReplacementRepositoryInterface_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockWordReplacementRepositoryInterface
func (_mock *MockWordReplacementRepositoryInterface) FindByID(ctx context.Context, id uint) (*models.WordReplacement, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.WordReplacement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*models.WordReplacement, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *models.WordReplacement); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WordReplacement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWordReplacementRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockWordReplacementRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockWordReplacementRepositoryInterface_Expecter) FindByID(ctx any, id any) *MockWordReplacementRepositoryInterface_FindByID_Call {
	return &MockWordReplacementRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockWordReplacementRepositoryInterface_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockWordReplacementRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_FindByID_Call) Return(wordReplacement *models.WordReplacement, err error) *MockWordReplacementRepositoryInterface_FindByID_Call {
	_c.Call.Return(wordReplacement, err)
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uint) (*models.WordReplacement, error)) *MockWordReplacementRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOriginal provides a mock function for the type MockWordReplacementRepositoryInterface
func (_mock *MockWordReplacementRepositoryInterface) FindByOriginal(ctx context.Context, original string) (*models.WordReplacement, error) {
	ret := _mock.Called(ctx, original)

	if len(ret) == 0 {
		panic("no return value specified for FindByOriginal")
	}

	var r0 *models.WordReplacement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.WordReplacement, error)); ok {
		return returnFunc(ctx, original)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.WordReplacement); ok {
		r0 = returnFunc(ctx, original)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WordReplacement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, original)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWordReplacementRepositoryInterface_FindByOriginal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOriginal'
type MockWordReplacementRepositoryInterface_FindByOriginal_Call struct {
	*mock.Call
}

// FindByOriginal is a helper method to define mock.On call
//   - ctx context.Context
//   - original string
func (_e *MockWordReplacementRepositoryInterface_Expecter) FindByOriginal(ctx any, original any) *MockWordReplacementRepositoryInterface_FindByOriginal_Call {
	return &MockWordReplacementRepositoryInterface_FindByOriginal_Call{Call: _e.mock.On("FindByOriginal", ctx, original)}
}

func (_c *MockWordReplacementRepositoryInterface_FindByOriginal_Call) Run(run func(ctx context.Context, original string)) *MockWordReplacementRepositoryInterface_FindByOriginal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_FindByOriginal_Call) Return(wordReplacement *models.WordReplacement, err error) *MockWordReplacementRepositoryInterface_FindByOriginal_Call {
	_c.Call.Return(wordReplacement, err)
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_FindByOriginal_Call) RunAndReturn(run func(ctx context.Context, original string) (*models.WordReplacement, error)) *MockWordReplacementRepositoryInterface_FindByOriginal_Call {
	_c.Call.Return(run)
	return _c
}

// GetReplacementMap provides a mock function for the type MockWordReplacementRepositoryInterface
func (_mock *MockWordReplacementRepositoryInterface) GetReplacementMap(ctx context.Context) (map[string]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReplacementMap")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWordReplacementRepositoryInterface_GetReplacementMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReplacementMap'
type MockWordReplacementRepositoryInterface_GetReplacementMap_Call struct {
	*mock.Call
}

// GetReplacementMap is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWordReplacementRepositoryInterface_Expecter) GetReplacementMap(ctx any) *MockWordReplacementRepositoryInterface_GetReplacementMap_Call {
	return &MockWordReplacementRepositoryInterface_GetReplacementMap_Call{Call: _e.mock.On("GetReplacementMap", ctx)}
}

func (_c *MockWordReplacementRepositoryInterface_GetReplacementMap_Call) Run(run func(ctx context.Context)) *MockWordReplacementRepositoryInterface_GetReplacementMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_GetReplacementMap_Call) Return(stringToString map[string]string, err error) *MockWordReplacementRepositoryInterface_GetReplacementMap_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_GetReplacementMap_Call) RunAndReturn(run func(ctx context.Context) (map[string]string, error)) *MockWordReplacementRepositoryInterface_GetReplacementMap_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWordReplacementRepositoryInterface
func (_mock *MockWordReplacementRepositoryInterface) List(ctx context.Context) ([]models.WordReplacement, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.WordReplacement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.WordReplacement, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.WordReplacement); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WordReplacement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWordReplacementRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWordReplacementRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWordReplacementRepositoryInterface_Expecter) List(ctx any) *MockWordReplacementRepositoryInterface_List_Call {
	return &MockWordReplacementRepositoryInterface_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockWordReplacementRepositoryInterface_List_Call) Run(run func(ctx context.Context)) *MockWordReplacementRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_List_Call) Return(wordReplacements []models.WordReplacement, err error) *MockWordReplacementRepositoryInterface_List_Call {
	_c.Call.Return(wordReplacements, err)
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_List_Call) RunAndReturn(run func(ctx context.Context) ([]models.WordReplacement, error)) *MockWordReplacementRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockWordReplacementRepositoryInterface
func (_mock *MockWordReplacementRepositoryInterface) Upsert(ctx context.Context, replacement *models.WordReplacement) error {
	ret := _mock.Called(ctx, replacement)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.WordReplacement) error); ok {
		r0 = returnFunc(ctx, replacement)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWordReplacementRepositoryInterface_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockWordReplacementRepositoryInterface_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - replacement *models.WordReplacement
func (_e *MockWordReplacementRepositoryInterface_Expecter) Upsert(ctx any, replacement any) *MockWordReplacementRepositoryInterface_Upsert_Call {
	return &MockWordReplacementRepositoryInterface_Upsert_Call{Call: _e.mock.On("Upsert", ctx, replacement)}
}

func (_c *MockWordReplacementRepositoryInterface_Upsert_Call) Run(run func(ctx context.Context, replacement *models.WordReplacement)) *MockWordReplacementRepositoryInterface_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.WordReplacement
		if args[1] != nil {
			arg1 = args[1].(*models.WordReplacement)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_Upsert_Call) Return(err error) *MockWordReplacementRepositoryInterface_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWordReplacementRepositoryInterface_Upsert_Call) RunAndReturn(run func(ctx context.Context, replacement *models.WordReplacement) error) *MockWordReplacementRepositoryInterface_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
