package batch

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/javinizer/javinizer-go/internal/api/contracts"
	"github.com/javinizer/javinizer-go/internal/api/testkit"
	"github.com/javinizer/javinizer-go/internal/config"
	"github.com/javinizer/javinizer-go/internal/models"
	"github.com/javinizer/javinizer-go/internal/worker/resultstore"
)

// TestRescrapeBatchMovie_TranslationWarningFields pins the wire contract that
// lets the review UI reconcile per-result translation warnings after a
// single-result rescrape: a warning generated BY the rescrape is surfaced on
// the response, and a clean rescrape omits both fields (omitempty) so the
// client can clear any stale warning from an earlier attempt. This endpoint
// issues no progress broadcast, so the response is the only carrier.
func TestRescrapeBatchMovie_TranslationWarningFields(t *testing.T) {
	initTestWebSocket(t)
	gin.SetMode(gin.TestMode)

	doRescrape := func(t *testing.T, cfg *config.Config) *httptest.ResponseRecorder {
		t.Helper()
		deps := createTestDeps(t, cfg, "")
		deps.CoreDeps.GetRegistry().RegisterInstance(&noPosterStubScraper{})

		job := createJobWithWF(deps, cfg, []string{"/tmp/IPX-951.mp4"})
		setJobResult(job, "/tmp/IPX-951.mp4", &resultstore.MovieResult{
			FileMatchInfo: models.FileMatchInfo{Path: "/tmp/IPX-951.mp4", MovieID: "IPX-951"},
			Status:        models.JobStatusCompleted,
			Movie:         &models.Movie{ID: "IPX-951", Title: "Old Title"},
		})

		router := gin.New()
		router.POST("/batch/:id/results/:resultId/rescrape", rescrapeBatchMovie(testkit.GetTestRuntime(deps)))

		body, err := json.Marshal(contracts.BatchRescrapeRequest{
			SelectedScrapers:  []string{"stub-no-poster"},
			ManualSearchInput: "IPX-951",
		})
		require.NoError(t, err)

		req := httptest.NewRequest(http.MethodPost, "/batch/"+job.GetID()+"/results/IPX-951/rescrape", bytes.NewBuffer(body))
		req.Header.Set("Content-Type", "application/json")
		rec := httptest.NewRecorder()
		router.ServeHTTP(rec, req)
		require.Equal(t, http.StatusOK, rec.Code, rec.Body.String())
		return rec
	}

	t.Run("warning produced by the rescrape is surfaced", func(t *testing.T) {
		// Undecodable translation payload -> typed parse error -> "unavailable".
		garbageSrv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			_, _ = w.Write([]byte("<html>Sorry... bot-block page</html>"))
		}))
		defer garbageSrv.Close()

		cfg := config.DefaultConfig(nil, nil)
		cfg.Metadata.Translation.Enabled = true
		cfg.Metadata.Translation.Provider = "google"
		cfg.Metadata.Translation.SourceLanguage = "ja"
		cfg.Metadata.Translation.TargetLanguage = "en"
		cfg.Metadata.Translation.Fields.Title = true
		cfg.Metadata.Translation.Google.Mode = models.GoogleModeFree
		cfg.Metadata.Translation.Google.BaseURL = garbageSrv.URL

		rec := doRescrape(t, cfg)

		var resp contracts.BatchRescrapeResponse
		require.NoError(t, json.Unmarshal(rec.Body.Bytes(), &resp))
		assert.Equal(t, "unavailable", resp.TranslationWarningCode)
		assert.NotEmpty(t, resp.TranslationWarning)
		assert.Contains(t, rec.Body.String(), `"translation_warning_code":"unavailable"`)
		assert.Contains(t, rec.Body.String(), `"translation_warning":"Translation (Google Translate (free))`)
	})

	t.Run("clean rescrape omits warning fields", func(t *testing.T) {
		cfg := config.DefaultConfig(nil, nil) // translation disabled by default

		rec := doRescrape(t, cfg)

		assert.NotContains(t, rec.Body.String(), "translation_warning",
			"a clean rescrape emits neither warning field (omitempty)")
		var resp contracts.BatchRescrapeResponse
		require.NoError(t, json.Unmarshal(rec.Body.Bytes(), &resp))
		assert.Empty(t, resp.TranslationWarning)
		assert.Empty(t, resp.TranslationWarningCode)
	})
}
