// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package workermocks

import (
	"context"

	"github.com/javinizer/javinizer-go/internal/models"
	"github.com/javinizer/javinizer-go/internal/operationmode"
	"github.com/javinizer/javinizer-go/internal/worker"
	"github.com/javinizer/javinizer-go/internal/workflow"
	mock "github.com/stretchr/testify/mock"
)

// NewMockControlledJob creates a new instance of MockControlledJob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockControlledJob(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockControlledJob {
	mock := &MockControlledJob{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockControlledJob is an autogenerated mock type for the ControlledJob type
type MockControlledJob struct {
	mock.Mock
}

type MockControlledJob_Expecter struct {
	mock *mock.Mock
}

func (_m *MockControlledJob) EXPECT() *MockControlledJob_Expecter {
	return &MockControlledJob_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) Cancel() {
	_mock.Called()
	return
}

// MockControlledJob_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockControlledJob_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
func (_e *MockControlledJob_Expecter) Cancel() *MockControlledJob_Cancel_Call {
	return &MockControlledJob_Cancel_Call{Call: _e.mock.On("Cancel")}
}

func (_c *MockControlledJob_Cancel_Call) Run(run func()) *MockControlledJob_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControlledJob_Cancel_Call) Return() *MockControlledJob_Cancel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControlledJob_Cancel_Call) RunAndReturn(run func()) *MockControlledJob_Cancel_Call {
	_c.Run(run)
	return _c
}

// Done provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) Done() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockControlledJob_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockControlledJob_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockControlledJob_Expecter) Done() *MockControlledJob_Done_Call {
	return &MockControlledJob_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockControlledJob_Done_Call) Run(run func()) *MockControlledJob_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControlledJob_Done_Call) Return(valCh <-chan struct{}) *MockControlledJob_Done_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockControlledJob_Done_Call) RunAndReturn(run func() <-chan struct{}) *MockControlledJob_Done_Call {
	_c.Call.Return(run)
	return _c
}

// FindFilePathsForMovieID provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) FindFilePathsForMovieID(movieID string) []string {
	ret := _mock.Called(movieID)

	if len(ret) == 0 {
		panic("no return value specified for FindFilePathsForMovieID")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(movieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockControlledJob_FindFilePathsForMovieID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFilePathsForMovieID'
type MockControlledJob_FindFilePathsForMovieID_Call struct {
	*mock.Call
}

// FindFilePathsForMovieID is a helper method to define mock.On call
//   - movieID string
func (_e *MockControlledJob_Expecter) FindFilePathsForMovieID(movieID any) *MockControlledJob_FindFilePathsForMovieID_Call {
	return &MockControlledJob_FindFilePathsForMovieID_Call{Call: _e.mock.On("FindFilePathsForMovieID", movieID)}
}

func (_c *MockControlledJob_FindFilePathsForMovieID_Call) Run(run func(movieID string)) *MockControlledJob_FindFilePathsForMovieID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControlledJob_FindFilePathsForMovieID_Call) Return(strings []string) *MockControlledJob_FindFilePathsForMovieID_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockControlledJob_FindFilePathsForMovieID_Call) RunAndReturn(run func(movieID string) []string) *MockControlledJob_FindFilePathsForMovieID_Call {
	_c.Call.Return(run)
	return _c
}

// FindMovieResultForMovieID provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) FindMovieResultForMovieID(movieID string) (*worker.MovieResult, error) {
	ret := _mock.Called(movieID)

	if len(ret) == 0 {
		panic("no return value specified for FindMovieResultForMovieID")
	}

	var r0 *worker.MovieResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*worker.MovieResult, error)); ok {
		return returnFunc(movieID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *worker.MovieResult); ok {
		r0 = returnFunc(movieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*worker.MovieResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(movieID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControlledJob_FindMovieResultForMovieID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMovieResultForMovieID'
type MockControlledJob_FindMovieResultForMovieID_Call struct {
	*mock.Call
}

// FindMovieResultForMovieID is a helper method to define mock.On call
//   - movieID string
func (_e *MockControlledJob_Expecter) FindMovieResultForMovieID(movieID any) *MockControlledJob_FindMovieResultForMovieID_Call {
	return &MockControlledJob_FindMovieResultForMovieID_Call{Call: _e.mock.On("FindMovieResultForMovieID", movieID)}
}

func (_c *MockControlledJob_FindMovieResultForMovieID_Call) Run(run func(movieID string)) *MockControlledJob_FindMovieResultForMovieID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControlledJob_FindMovieResultForMovieID_Call) Return(movieResult *worker.MovieResult, err error) *MockControlledJob_FindMovieResultForMovieID_Call {
	_c.Call.Return(movieResult, err)
	return _c
}

func (_c *MockControlledJob_FindMovieResultForMovieID_Call) RunAndReturn(run func(movieID string) (*worker.MovieResult, error)) *MockControlledJob_FindMovieResultForMovieID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileMatchInfosForMovieID provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) GetFileMatchInfosForMovieID(movieID string) []models.FileMatchInfo {
	ret := _mock.Called(movieID)

	if len(ret) == 0 {
		panic("no return value specified for GetFileMatchInfosForMovieID")
	}

	var r0 []models.FileMatchInfo
	if returnFunc, ok := ret.Get(0).(func(string) []models.FileMatchInfo); ok {
		r0 = returnFunc(movieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FileMatchInfo)
		}
	}
	return r0
}

// MockControlledJob_GetFileMatchInfosForMovieID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileMatchInfosForMovieID'
type MockControlledJob_GetFileMatchInfosForMovieID_Call struct {
	*mock.Call
}

// GetFileMatchInfosForMovieID is a helper method to define mock.On call
//   - movieID string
func (_e *MockControlledJob_Expecter) GetFileMatchInfosForMovieID(movieID any) *MockControlledJob_GetFileMatchInfosForMovieID_Call {
	return &MockControlledJob_GetFileMatchInfosForMovieID_Call{Call: _e.mock.On("GetFileMatchInfosForMovieID", movieID)}
}

func (_c *MockControlledJob_GetFileMatchInfosForMovieID_Call) Run(run func(movieID string)) *MockControlledJob_GetFileMatchInfosForMovieID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControlledJob_GetFileMatchInfosForMovieID_Call) Return(fileMatchInfos []models.FileMatchInfo) *MockControlledJob_GetFileMatchInfosForMovieID_Call {
	_c.Call.Return(fileMatchInfos)
	return _c
}

func (_c *MockControlledJob_GetFileMatchInfosForMovieID_Call) RunAndReturn(run func(movieID string) []models.FileMatchInfo) *MockControlledJob_GetFileMatchInfosForMovieID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileResultByResultID provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) GetFileResultByResultID(resultID string) (*worker.MovieResult, string, bool) {
	ret := _mock.Called(resultID)

	if len(ret) == 0 {
		panic("no return value specified for GetFileResultByResultID")
	}

	var r0 *worker.MovieResult
	var r1 string
	var r2 bool
	if returnFunc, ok := ret.Get(0).(func(string) (*worker.MovieResult, string, bool)); ok {
		return returnFunc(resultID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *worker.MovieResult); ok {
		r0 = returnFunc(resultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*worker.MovieResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) string); ok {
		r1 = returnFunc(resultID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string) bool); ok {
		r2 = returnFunc(resultID)
	} else {
		r2 = ret.Get(2).(bool)
	}
	return r0, r1, r2
}

// MockControlledJob_GetFileResultByResultID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileResultByResultID'
type MockControlledJob_GetFileResultByResultID_Call struct {
	*mock.Call
}

// GetFileResultByResultID is a helper method to define mock.On call
//   - resultID string
func (_e *MockControlledJob_Expecter) GetFileResultByResultID(resultID any) *MockControlledJob_GetFileResultByResultID_Call {
	return &MockControlledJob_GetFileResultByResultID_Call{Call: _e.mock.On("GetFileResultByResultID", resultID)}
}

func (_c *MockControlledJob_GetFileResultByResultID_Call) Run(run func(resultID string)) *MockControlledJob_GetFileResultByResultID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControlledJob_GetFileResultByResultID_Call) Return(movieResult *worker.MovieResult, s string, b bool) *MockControlledJob_GetFileResultByResultID_Call {
	_c.Call.Return(movieResult, s, b)
	return _c
}

func (_c *MockControlledJob_GetFileResultByResultID_Call) RunAndReturn(run func(resultID string) (*worker.MovieResult, string, bool)) *MockControlledJob_GetFileResultByResultID_Call {
	_c.Call.Return(run)
	return _c
}

// GetID provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) GetID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockControlledJob_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type MockControlledJob_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *MockControlledJob_Expecter) GetID() *MockControlledJob_GetID_Call {
	return &MockControlledJob_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *MockControlledJob_GetID_Call) Run(run func()) *MockControlledJob_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControlledJob_GetID_Call) Return(s string) *MockControlledJob_GetID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockControlledJob_GetID_Call) RunAndReturn(run func() string) *MockControlledJob_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobStatus provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) GetJobStatus() models.JobStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetJobStatus")
	}

	var r0 models.JobStatus
	if returnFunc, ok := ret.Get(0).(func() models.JobStatus); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(models.JobStatus)
	}
	return r0
}

// MockControlledJob_GetJobStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobStatus'
type MockControlledJob_GetJobStatus_Call struct {
	*mock.Call
}

// GetJobStatus is a helper method to define mock.On call
func (_e *MockControlledJob_Expecter) GetJobStatus() *MockControlledJob_GetJobStatus_Call {
	return &MockControlledJob_GetJobStatus_Call{Call: _e.mock.On("GetJobStatus")}
}

func (_c *MockControlledJob_GetJobStatus_Call) Run(run func()) *MockControlledJob_GetJobStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControlledJob_GetJobStatus_Call) Return(jobStatus models.JobStatus) *MockControlledJob_GetJobStatus_Call {
	_c.Call.Return(jobStatus)
	return _c
}

func (_c *MockControlledJob_GetJobStatus_Call) RunAndReturn(run func() models.JobStatus) *MockControlledJob_GetJobStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetMovieResult provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) GetMovieResult(filePath string) (*worker.MovieResult, error) {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieResult")
	}

	var r0 *worker.MovieResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*worker.MovieResult, error)); ok {
		return returnFunc(filePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *worker.MovieResult); ok {
		r0 = returnFunc(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*worker.MovieResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControlledJob_GetMovieResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovieResult'
type MockControlledJob_GetMovieResult_Call struct {
	*mock.Call
}

// GetMovieResult is a helper method to define mock.On call
//   - filePath string
func (_e *MockControlledJob_Expecter) GetMovieResult(filePath any) *MockControlledJob_GetMovieResult_Call {
	return &MockControlledJob_GetMovieResult_Call{Call: _e.mock.On("GetMovieResult", filePath)}
}

func (_c *MockControlledJob_GetMovieResult_Call) Run(run func(filePath string)) *MockControlledJob_GetMovieResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControlledJob_GetMovieResult_Call) Return(movieResult *worker.MovieResult, err error) *MockControlledJob_GetMovieResult_Call {
	_c.Call.Return(movieResult, err)
	return _c
}

func (_c *MockControlledJob_GetMovieResult_Call) RunAndReturn(run func(filePath string) (*worker.MovieResult, error)) *MockControlledJob_GetMovieResult_Call {
	_c.Call.Return(run)
	return _c
}

// GetMovieResultsForMovieID provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) GetMovieResultsForMovieID(movieID string) []*worker.MovieResult {
	ret := _mock.Called(movieID)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieResultsForMovieID")
	}

	var r0 []*worker.MovieResult
	if returnFunc, ok := ret.Get(0).(func(string) []*worker.MovieResult); ok {
		r0 = returnFunc(movieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*worker.MovieResult)
		}
	}
	return r0
}

// MockControlledJob_GetMovieResultsForMovieID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovieResultsForMovieID'
type MockControlledJob_GetMovieResultsForMovieID_Call struct {
	*mock.Call
}

// GetMovieResultsForMovieID is a helper method to define mock.On call
//   - movieID string
func (_e *MockControlledJob_Expecter) GetMovieResultsForMovieID(movieID any) *MockControlledJob_GetMovieResultsForMovieID_Call {
	return &MockControlledJob_GetMovieResultsForMovieID_Call{Call: _e.mock.On("GetMovieResultsForMovieID", movieID)}
}

func (_c *MockControlledJob_GetMovieResultsForMovieID_Call) Run(run func(movieID string)) *MockControlledJob_GetMovieResultsForMovieID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControlledJob_GetMovieResultsForMovieID_Call) Return(movieResults []*worker.MovieResult) *MockControlledJob_GetMovieResultsForMovieID_Call {
	_c.Call.Return(movieResults)
	return _c
}

func (_c *MockControlledJob_GetMovieResultsForMovieID_Call) RunAndReturn(run func(movieID string) []*worker.MovieResult) *MockControlledJob_GetMovieResultsForMovieID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProvenance provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) GetProvenance(filePath string) *worker.ProvenanceData {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for GetProvenance")
	}

	var r0 *worker.ProvenanceData
	if returnFunc, ok := ret.Get(0).(func(string) *worker.ProvenanceData); ok {
		r0 = returnFunc(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*worker.ProvenanceData)
		}
	}
	return r0
}

// MockControlledJob_GetProvenance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProvenance'
type MockControlledJob_GetProvenance_Call struct {
	*mock.Call
}

// GetProvenance is a helper method to define mock.On call
//   - filePath string
func (_e *MockControlledJob_Expecter) GetProvenance(filePath any) *MockControlledJob_GetProvenance_Call {
	return &MockControlledJob_GetProvenance_Call{Call: _e.mock.On("GetProvenance", filePath)}
}

func (_c *MockControlledJob_GetProvenance_Call) Run(run func(filePath string)) *MockControlledJob_GetProvenance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControlledJob_GetProvenance_Call) Return(provenanceData *worker.ProvenanceData) *MockControlledJob_GetProvenance_Call {
	_c.Call.Return(provenanceData)
	return _c
}

func (_c *MockControlledJob_GetProvenance_Call) RunAndReturn(run func(filePath string) *worker.ProvenanceData) *MockControlledJob_GetProvenance_Call {
	_c.Call.Return(run)
	return _c
}

// GetResults provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) GetResults() []worker.MovieResult {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResults")
	}

	var r0 []worker.MovieResult
	if returnFunc, ok := ret.Get(0).(func() []worker.MovieResult); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]worker.MovieResult)
		}
	}
	return r0
}

// MockControlledJob_GetResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResults'
type MockControlledJob_GetResults_Call struct {
	*mock.Call
}

// GetResults is a helper method to define mock.On call
func (_e *MockControlledJob_Expecter) GetResults() *MockControlledJob_GetResults_Call {
	return &MockControlledJob_GetResults_Call{Call: _e.mock.On("GetResults")}
}

func (_c *MockControlledJob_GetResults_Call) Run(run func()) *MockControlledJob_GetResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControlledJob_GetResults_Call) Return(movieResults []worker.MovieResult) *MockControlledJob_GetResults_Call {
	_c.Call.Return(movieResults)
	return _c
}

func (_c *MockControlledJob_GetResults_Call) RunAndReturn(run func() []worker.MovieResult) *MockControlledJob_GetResults_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) GetStatus() *worker.BatchJobStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 *worker.BatchJobStatus
	if returnFunc, ok := ret.Get(0).(func() *worker.BatchJobStatus); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*worker.BatchJobStatus)
		}
	}
	return r0
}

// MockControlledJob_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockControlledJob_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
func (_e *MockControlledJob_Expecter) GetStatus() *MockControlledJob_GetStatus_Call {
	return &MockControlledJob_GetStatus_Call{Call: _e.mock.On("GetStatus")}
}

func (_c *MockControlledJob_GetStatus_Call) Run(run func()) *MockControlledJob_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControlledJob_GetStatus_Call) Return(batchJobStatus *worker.BatchJobStatus) *MockControlledJob_GetStatus_Call {
	_c.Call.Return(batchJobStatus)
	return _c
}

func (_c *MockControlledJob_GetStatus_Call) RunAndReturn(run func() *worker.BatchJobStatus) *MockControlledJob_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// MarkReverted provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) MarkReverted() {
	_mock.Called()
	return
}

// MockControlledJob_MarkReverted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkReverted'
type MockControlledJob_MarkReverted_Call struct {
	*mock.Call
}

// MarkReverted is a helper method to define mock.On call
func (_e *MockControlledJob_Expecter) MarkReverted() *MockControlledJob_MarkReverted_Call {
	return &MockControlledJob_MarkReverted_Call{Call: _e.mock.On("MarkReverted")}
}

func (_c *MockControlledJob_MarkReverted_Call) Run(run func()) *MockControlledJob_MarkReverted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControlledJob_MarkReverted_Call) Return() *MockControlledJob_MarkReverted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControlledJob_MarkReverted_Call) RunAndReturn(run func()) *MockControlledJob_MarkReverted_Call {
	_c.Run(run)
	return _c
}

// Rescrape provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) Rescrape(ctx context.Context, cmd worker.RescrapeCmd) (*worker.RescrapeResult, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Rescrape")
	}

	var r0 *worker.RescrapeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, worker.RescrapeCmd) (*worker.RescrapeResult, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, worker.RescrapeCmd) *worker.RescrapeResult); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*worker.RescrapeResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, worker.RescrapeCmd) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControlledJob_Rescrape_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rescrape'
type MockControlledJob_Rescrape_Call struct {
	*mock.Call
}

// Rescrape is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd worker.RescrapeCmd
func (_e *MockControlledJob_Expecter) Rescrape(ctx any, cmd any) *MockControlledJob_Rescrape_Call {
	return &MockControlledJob_Rescrape_Call{Call: _e.mock.On("Rescrape", ctx, cmd)}
}

func (_c *MockControlledJob_Rescrape_Call) Run(run func(ctx context.Context, cmd worker.RescrapeCmd)) *MockControlledJob_Rescrape_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 worker.RescrapeCmd
		if args[1] != nil {
			arg1 = args[1].(worker.RescrapeCmd)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControlledJob_Rescrape_Call) Return(rescrapeResult *worker.RescrapeResult, err error) *MockControlledJob_Rescrape_Call {
	_c.Call.Return(rescrapeResult, err)
	return _c
}

func (_c *MockControlledJob_Rescrape_Call) RunAndReturn(run func(ctx context.Context, cmd worker.RescrapeCmd) (*worker.RescrapeResult, error)) *MockControlledJob_Rescrape_Call {
	_c.Call.Return(run)
	return _c
}

// SetBatchCfg provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) SetBatchCfg(cfg worker.BatchJobConfig) {
	_mock.Called(cfg)
	return
}

// MockControlledJob_SetBatchCfg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBatchCfg'
type MockControlledJob_SetBatchCfg_Call struct {
	*mock.Call
}

// SetBatchCfg is a helper method to define mock.On call
//   - cfg worker.BatchJobConfig
func (_e *MockControlledJob_Expecter) SetBatchCfg(cfg any) *MockControlledJob_SetBatchCfg_Call {
	return &MockControlledJob_SetBatchCfg_Call{Call: _e.mock.On("SetBatchCfg", cfg)}
}

func (_c *MockControlledJob_SetBatchCfg_Call) Run(run func(cfg worker.BatchJobConfig)) *MockControlledJob_SetBatchCfg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 worker.BatchJobConfig
		if args[0] != nil {
			arg0 = args[0].(worker.BatchJobConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControlledJob_SetBatchCfg_Call) Return() *MockControlledJob_SetBatchCfg_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControlledJob_SetBatchCfg_Call) RunAndReturn(run func(cfg worker.BatchJobConfig)) *MockControlledJob_SetBatchCfg_Call {
	_c.Run(run)
	return _c
}

// SetJobStatus provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) SetJobStatus(status models.JobStatus) {
	_mock.Called(status)
	return
}

// MockControlledJob_SetJobStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetJobStatus'
type MockControlledJob_SetJobStatus_Call struct {
	*mock.Call
}

// SetJobStatus is a helper method to define mock.On call
//   - status models.JobStatus
func (_e *MockControlledJob_Expecter) SetJobStatus(status any) *MockControlledJob_SetJobStatus_Call {
	return &MockControlledJob_SetJobStatus_Call{Call: _e.mock.On("SetJobStatus", status)}
}

func (_c *MockControlledJob_SetJobStatus_Call) Run(run func(status models.JobStatus)) *MockControlledJob_SetJobStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.JobStatus
		if args[0] != nil {
			arg0 = args[0].(models.JobStatus)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControlledJob_SetJobStatus_Call) Return() *MockControlledJob_SetJobStatus_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControlledJob_SetJobStatus_Call) RunAndReturn(run func(status models.JobStatus)) *MockControlledJob_SetJobStatus_Call {
	_c.Run(run)
	return _c
}

// SetOperationModeOverride provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) SetOperationModeOverride(mode operationmode.OperationMode) error {
	ret := _mock.Called(mode)

	if len(ret) == 0 {
		panic("no return value specified for SetOperationModeOverride")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(operationmode.OperationMode) error); ok {
		r0 = returnFunc(mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControlledJob_SetOperationModeOverride_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOperationModeOverride'
type MockControlledJob_SetOperationModeOverride_Call struct {
	*mock.Call
}

// SetOperationModeOverride is a helper method to define mock.On call
//   - mode operationmode.OperationMode
func (_e *MockControlledJob_Expecter) SetOperationModeOverride(mode any) *MockControlledJob_SetOperationModeOverride_Call {
	return &MockControlledJob_SetOperationModeOverride_Call{Call: _e.mock.On("SetOperationModeOverride", mode)}
}

func (_c *MockControlledJob_SetOperationModeOverride_Call) Run(run func(mode operationmode.OperationMode)) *MockControlledJob_SetOperationModeOverride_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 operationmode.OperationMode
		if args[0] != nil {
			arg0 = args[0].(operationmode.OperationMode)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControlledJob_SetOperationModeOverride_Call) Return(err error) *MockControlledJob_SetOperationModeOverride_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControlledJob_SetOperationModeOverride_Call) RunAndReturn(run func(mode operationmode.OperationMode) error) *MockControlledJob_SetOperationModeOverride_Call {
	_c.Call.Return(run)
	return _c
}

// SetPersistError provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) SetPersistError(msg string) {
	_mock.Called(msg)
	return
}

// MockControlledJob_SetPersistError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPersistError'
type MockControlledJob_SetPersistError_Call struct {
	*mock.Call
}

// SetPersistError is a helper method to define mock.On call
//   - msg string
func (_e *MockControlledJob_Expecter) SetPersistError(msg any) *MockControlledJob_SetPersistError_Call {
	return &MockControlledJob_SetPersistError_Call{Call: _e.mock.On("SetPersistError", msg)}
}

func (_c *MockControlledJob_SetPersistError_Call) Run(run func(msg string)) *MockControlledJob_SetPersistError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControlledJob_SetPersistError_Call) Return() *MockControlledJob_SetPersistError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControlledJob_SetPersistError_Call) RunAndReturn(run func(msg string)) *MockControlledJob_SetPersistError_Call {
	_c.Run(run)
	return _c
}

// SetWorkflow provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) SetWorkflow(wf workflow.WorkflowInterface) {
	_mock.Called(wf)
	return
}

// MockControlledJob_SetWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWorkflow'
type MockControlledJob_SetWorkflow_Call struct {
	*mock.Call
}

// SetWorkflow is a helper method to define mock.On call
//   - wf workflow.WorkflowInterface
func (_e *MockControlledJob_Expecter) SetWorkflow(wf any) *MockControlledJob_SetWorkflow_Call {
	return &MockControlledJob_SetWorkflow_Call{Call: _e.mock.On("SetWorkflow", wf)}
}

func (_c *MockControlledJob_SetWorkflow_Call) Run(run func(wf workflow.WorkflowInterface)) *MockControlledJob_SetWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 workflow.WorkflowInterface
		if args[0] != nil {
			arg0 = args[0].(workflow.WorkflowInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControlledJob_SetWorkflow_Call) Return() *MockControlledJob_SetWorkflow_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControlledJob_SetWorkflow_Call) RunAndReturn(run func(wf workflow.WorkflowInterface)) *MockControlledJob_SetWorkflow_Call {
	_c.Run(run)
	return _c
}

// StartApply provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) StartApply(ctx context.Context, cfg worker.ApplyPhaseConfig) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for StartApply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, worker.ApplyPhaseConfig) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControlledJob_StartApply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartApply'
type MockControlledJob_StartApply_Call struct {
	*mock.Call
}

// StartApply is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg worker.ApplyPhaseConfig
func (_e *MockControlledJob_Expecter) StartApply(ctx any, cfg any) *MockControlledJob_StartApply_Call {
	return &MockControlledJob_StartApply_Call{Call: _e.mock.On("StartApply", ctx, cfg)}
}

func (_c *MockControlledJob_StartApply_Call) Run(run func(ctx context.Context, cfg worker.ApplyPhaseConfig)) *MockControlledJob_StartApply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 worker.ApplyPhaseConfig
		if args[1] != nil {
			arg1 = args[1].(worker.ApplyPhaseConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockControlledJob_StartApply_Call) Return(err error) *MockControlledJob_StartApply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControlledJob_StartApply_Call) RunAndReturn(run func(ctx context.Context, cfg worker.ApplyPhaseConfig) error) *MockControlledJob_StartApply_Call {
	_c.Call.Return(run)
	return _c
}

// StartScrape provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) StartScrape(ctx context.Context, files []string, cfg worker.ScrapePhaseConfig) error {
	ret := _mock.Called(ctx, files, cfg)

	if len(ret) == 0 {
		panic("no return value specified for StartScrape")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, worker.ScrapePhaseConfig) error); ok {
		r0 = returnFunc(ctx, files, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControlledJob_StartScrape_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartScrape'
type MockControlledJob_StartScrape_Call struct {
	*mock.Call
}

// StartScrape is a helper method to define mock.On call
//   - ctx context.Context
//   - files []string
//   - cfg worker.ScrapePhaseConfig
func (_e *MockControlledJob_Expecter) StartScrape(ctx any, files any, cfg any) *MockControlledJob_StartScrape_Call {
	return &MockControlledJob_StartScrape_Call{Call: _e.mock.On("StartScrape", ctx, files, cfg)}
}

func (_c *MockControlledJob_StartScrape_Call) Run(run func(ctx context.Context, files []string, cfg worker.ScrapePhaseConfig)) *MockControlledJob_StartScrape_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 worker.ScrapePhaseConfig
		if args[2] != nil {
			arg2 = args[2].(worker.ScrapePhaseConfig)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockControlledJob_StartScrape_Call) Return(err error) *MockControlledJob_StartScrape_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControlledJob_StartScrape_Call) RunAndReturn(run func(ctx context.Context, files []string, cfg worker.ScrapePhaseConfig) error) *MockControlledJob_StartScrape_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) Subscribe() worker.JobEventSubscriber {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 worker.JobEventSubscriber
	if returnFunc, ok := ret.Get(0).(func() worker.JobEventSubscriber); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(worker.JobEventSubscriber)
		}
	}
	return r0
}

// MockControlledJob_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockControlledJob_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
func (_e *MockControlledJob_Expecter) Subscribe() *MockControlledJob_Subscribe_Call {
	return &MockControlledJob_Subscribe_Call{Call: _e.mock.On("Subscribe")}
}

func (_c *MockControlledJob_Subscribe_Call) Run(run func()) *MockControlledJob_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControlledJob_Subscribe_Call) Return(jobEventSubscriber worker.JobEventSubscriber) *MockControlledJob_Subscribe_Call {
	_c.Call.Return(jobEventSubscriber)
	return _c
}

func (_c *MockControlledJob_Subscribe_Call) RunAndReturn(run func() worker.JobEventSubscriber) *MockControlledJob_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockControlledJob
func (_mock *MockControlledJob) Wait() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockControlledJob_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockControlledJob_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *MockControlledJob_Expecter) Wait() *MockControlledJob_Wait_Call {
	return &MockControlledJob_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *MockControlledJob_Wait_Call) Run(run func()) *MockControlledJob_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControlledJob_Wait_Call) Return(err error) *MockControlledJob_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockControlledJob_Wait_Call) RunAndReturn(run func() error) *MockControlledJob_Wait_Call {
	_c.Call.Return(run)
	return _c
}
