// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package workermocks

import (
	"context"

	"github.com/javinizer/javinizer-go/internal/models"
	"github.com/javinizer/javinizer-go/internal/worker"
	"github.com/javinizer/javinizer-go/internal/worker/resultstore"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEditableJob creates a new instance of MockEditableJob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEditableJob(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEditableJob {
	mock := &MockEditableJob{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEditableJob is an autogenerated mock type for the EditableJob type
type MockEditableJob struct {
	mock.Mock
}

type MockEditableJob_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEditableJob) EXPECT() *MockEditableJob_Expecter {
	return &MockEditableJob_Expecter{mock: &_m.Mock}
}

// ApplyFieldOverride provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) ApplyFieldOverride(ctx context.Context, resultID string, fieldKey string, source string) (*resultstore.MovieResult, *resultstore.ProvenanceData, error) {
	ret := _mock.Called(ctx, resultID, fieldKey, source)

	if len(ret) == 0 {
		panic("no return value specified for ApplyFieldOverride")
	}

	var r0 *resultstore.MovieResult
	var r1 *resultstore.ProvenanceData
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*resultstore.MovieResult, *resultstore.ProvenanceData, error)); ok {
		return returnFunc(ctx, resultID, fieldKey, source)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *resultstore.MovieResult); ok {
		r0 = returnFunc(ctx, resultID, fieldKey, source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resultstore.MovieResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) *resultstore.ProvenanceData); ok {
		r1 = returnFunc(ctx, resultID, fieldKey, source)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*resultstore.ProvenanceData)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(ctx, resultID, fieldKey, source)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockEditableJob_ApplyFieldOverride_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyFieldOverride'
type MockEditableJob_ApplyFieldOverride_Call struct {
	*mock.Call
}

// ApplyFieldOverride is a helper method to define mock.On call
//   - ctx context.Context
//   - resultID string
//   - fieldKey string
//   - source string
func (_e *MockEditableJob_Expecter) ApplyFieldOverride(ctx any, resultID any, fieldKey any, source any) *MockEditableJob_ApplyFieldOverride_Call {
	return &MockEditableJob_ApplyFieldOverride_Call{Call: _e.mock.On("ApplyFieldOverride", ctx, resultID, fieldKey, source)}
}

func (_c *MockEditableJob_ApplyFieldOverride_Call) Run(run func(ctx context.Context, resultID string, fieldKey string, source string)) *MockEditableJob_ApplyFieldOverride_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEditableJob_ApplyFieldOverride_Call) Return(movieResult *resultstore.MovieResult, provenanceData *resultstore.ProvenanceData, err error) *MockEditableJob_ApplyFieldOverride_Call {
	_c.Call.Return(movieResult, provenanceData, err)
	return _c
}

func (_c *MockEditableJob_ApplyFieldOverride_Call) RunAndReturn(run func(ctx context.Context, resultID string, fieldKey string, source string) (*resultstore.MovieResult, *resultstore.ProvenanceData, error)) *MockEditableJob_ApplyFieldOverride_Call {
	_c.Call.Return(run)
	return _c
}

// ExcludeFile provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) ExcludeFile(filePath string) {
	_mock.Called(filePath)
	return
}

// MockEditableJob_ExcludeFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExcludeFile'
type MockEditableJob_ExcludeFile_Call struct {
	*mock.Call
}

// ExcludeFile is a helper method to define mock.On call
//   - filePath string
func (_e *MockEditableJob_Expecter) ExcludeFile(filePath any) *MockEditableJob_ExcludeFile_Call {
	return &MockEditableJob_ExcludeFile_Call{Call: _e.mock.On("ExcludeFile", filePath)}
}

func (_c *MockEditableJob_ExcludeFile_Call) Run(run func(filePath string)) *MockEditableJob_ExcludeFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEditableJob_ExcludeFile_Call) Return() *MockEditableJob_ExcludeFile_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEditableJob_ExcludeFile_Call) RunAndReturn(run func(filePath string)) *MockEditableJob_ExcludeFile_Call {
	_c.Run(run)
	return _c
}

// ExcludeMovieFamily provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) ExcludeMovieFamily(ctx context.Context, movieID string) error {
	ret := _mock.Called(ctx, movieID)

	if len(ret) == 0 {
		panic("no return value specified for ExcludeMovieFamily")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, movieID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEditableJob_ExcludeMovieFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExcludeMovieFamily'
type MockEditableJob_ExcludeMovieFamily_Call struct {
	*mock.Call
}

// ExcludeMovieFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - movieID string
func (_e *MockEditableJob_Expecter) ExcludeMovieFamily(ctx any, movieID any) *MockEditableJob_ExcludeMovieFamily_Call {
	return &MockEditableJob_ExcludeMovieFamily_Call{Call: _e.mock.On("ExcludeMovieFamily", ctx, movieID)}
}

func (_c *MockEditableJob_ExcludeMovieFamily_Call) Run(run func(ctx context.Context, movieID string)) *MockEditableJob_ExcludeMovieFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEditableJob_ExcludeMovieFamily_Call) Return(err error) *MockEditableJob_ExcludeMovieFamily_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEditableJob_ExcludeMovieFamily_Call) RunAndReturn(run func(ctx context.Context, movieID string) error) *MockEditableJob_ExcludeMovieFamily_Call {
	_c.Call.Return(run)
	return _c
}

// FindFilePathsForMovieID provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) FindFilePathsForMovieID(movieID string) []string {
	ret := _mock.Called(movieID)

	if len(ret) == 0 {
		panic("no return value specified for FindFilePathsForMovieID")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(movieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockEditableJob_FindFilePathsForMovieID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFilePathsForMovieID'
type MockEditableJob_FindFilePathsForMovieID_Call struct {
	*mock.Call
}

// FindFilePathsForMovieID is a helper method to define mock.On call
//   - movieID string
func (_e *MockEditableJob_Expecter) FindFilePathsForMovieID(movieID any) *MockEditableJob_FindFilePathsForMovieID_Call {
	return &MockEditableJob_FindFilePathsForMovieID_Call{Call: _e.mock.On("FindFilePathsForMovieID", movieID)}
}

func (_c *MockEditableJob_FindFilePathsForMovieID_Call) Run(run func(movieID string)) *MockEditableJob_FindFilePathsForMovieID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEditableJob_FindFilePathsForMovieID_Call) Return(strings []string) *MockEditableJob_FindFilePathsForMovieID_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockEditableJob_FindFilePathsForMovieID_Call) RunAndReturn(run func(movieID string) []string) *MockEditableJob_FindFilePathsForMovieID_Call {
	_c.Call.Return(run)
	return _c
}

// FindMovieResultForMovieID provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) FindMovieResultForMovieID(movieID string) (*resultstore.MovieResult, error) {
	ret := _mock.Called(movieID)

	if len(ret) == 0 {
		panic("no return value specified for FindMovieResultForMovieID")
	}

	var r0 *resultstore.MovieResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*resultstore.MovieResult, error)); ok {
		return returnFunc(movieID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *resultstore.MovieResult); ok {
		r0 = returnFunc(movieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resultstore.MovieResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(movieID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEditableJob_FindMovieResultForMovieID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMovieResultForMovieID'
type MockEditableJob_FindMovieResultForMovieID_Call struct {
	*mock.Call
}

// FindMovieResultForMovieID is a helper method to define mock.On call
//   - movieID string
func (_e *MockEditableJob_Expecter) FindMovieResultForMovieID(movieID any) *MockEditableJob_FindMovieResultForMovieID_Call {
	return &MockEditableJob_FindMovieResultForMovieID_Call{Call: _e.mock.On("FindMovieResultForMovieID", movieID)}
}

func (_c *MockEditableJob_FindMovieResultForMovieID_Call) Run(run func(movieID string)) *MockEditableJob_FindMovieResultForMovieID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEditableJob_FindMovieResultForMovieID_Call) Return(movieResult *resultstore.MovieResult, err error) *MockEditableJob_FindMovieResultForMovieID_Call {
	_c.Call.Return(movieResult, err)
	return _c
}

func (_c *MockEditableJob_FindMovieResultForMovieID_Call) RunAndReturn(run func(movieID string) (*resultstore.MovieResult, error)) *MockEditableJob_FindMovieResultForMovieID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentPhase provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) GetCurrentPhase() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentPhase")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEditableJob_GetCurrentPhase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentPhase'
type MockEditableJob_GetCurrentPhase_Call struct {
	*mock.Call
}

// GetCurrentPhase is a helper method to define mock.On call
func (_e *MockEditableJob_Expecter) GetCurrentPhase() *MockEditableJob_GetCurrentPhase_Call {
	return &MockEditableJob_GetCurrentPhase_Call{Call: _e.mock.On("GetCurrentPhase")}
}

func (_c *MockEditableJob_GetCurrentPhase_Call) Run(run func()) *MockEditableJob_GetCurrentPhase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditableJob_GetCurrentPhase_Call) Return(s string) *MockEditableJob_GetCurrentPhase_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEditableJob_GetCurrentPhase_Call) RunAndReturn(run func() string) *MockEditableJob_GetCurrentPhase_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileMatchInfosForMovieID provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) GetFileMatchInfosForMovieID(movieID string) []models.FileMatchInfo {
	ret := _mock.Called(movieID)

	if len(ret) == 0 {
		panic("no return value specified for GetFileMatchInfosForMovieID")
	}

	var r0 []models.FileMatchInfo
	if returnFunc, ok := ret.Get(0).(func(string) []models.FileMatchInfo); ok {
		r0 = returnFunc(movieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FileMatchInfo)
		}
	}
	return r0
}

// MockEditableJob_GetFileMatchInfosForMovieID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileMatchInfosForMovieID'
type MockEditableJob_GetFileMatchInfosForMovieID_Call struct {
	*mock.Call
}

// GetFileMatchInfosForMovieID is a helper method to define mock.On call
//   - movieID string
func (_e *MockEditableJob_Expecter) GetFileMatchInfosForMovieID(movieID any) *MockEditableJob_GetFileMatchInfosForMovieID_Call {
	return &MockEditableJob_GetFileMatchInfosForMovieID_Call{Call: _e.mock.On("GetFileMatchInfosForMovieID", movieID)}
}

func (_c *MockEditableJob_GetFileMatchInfosForMovieID_Call) Run(run func(movieID string)) *MockEditableJob_GetFileMatchInfosForMovieID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEditableJob_GetFileMatchInfosForMovieID_Call) Return(fileMatchInfos []models.FileMatchInfo) *MockEditableJob_GetFileMatchInfosForMovieID_Call {
	_c.Call.Return(fileMatchInfos)
	return _c
}

func (_c *MockEditableJob_GetFileMatchInfosForMovieID_Call) RunAndReturn(run func(movieID string) []models.FileMatchInfo) *MockEditableJob_GetFileMatchInfosForMovieID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileResultByResultID provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) GetFileResultByResultID(resultID string) (*resultstore.MovieResult, string, bool) {
	ret := _mock.Called(resultID)

	if len(ret) == 0 {
		panic("no return value specified for GetFileResultByResultID")
	}

	var r0 *resultstore.MovieResult
	var r1 string
	var r2 bool
	if returnFunc, ok := ret.Get(0).(func(string) (*resultstore.MovieResult, string, bool)); ok {
		return returnFunc(resultID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *resultstore.MovieResult); ok {
		r0 = returnFunc(resultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resultstore.MovieResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) string); ok {
		r1 = returnFunc(resultID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string) bool); ok {
		r2 = returnFunc(resultID)
	} else {
		r2 = ret.Get(2).(bool)
	}
	return r0, r1, r2
}

// MockEditableJob_GetFileResultByResultID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileResultByResultID'
type MockEditableJob_GetFileResultByResultID_Call struct {
	*mock.Call
}

// GetFileResultByResultID is a helper method to define mock.On call
//   - resultID string
func (_e *MockEditableJob_Expecter) GetFileResultByResultID(resultID any) *MockEditableJob_GetFileResultByResultID_Call {
	return &MockEditableJob_GetFileResultByResultID_Call{Call: _e.mock.On("GetFileResultByResultID", resultID)}
}

func (_c *MockEditableJob_GetFileResultByResultID_Call) Run(run func(resultID string)) *MockEditableJob_GetFileResultByResultID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEditableJob_GetFileResultByResultID_Call) Return(movieResult *resultstore.MovieResult, s string, b bool) *MockEditableJob_GetFileResultByResultID_Call {
	_c.Call.Return(movieResult, s, b)
	return _c
}

func (_c *MockEditableJob_GetFileResultByResultID_Call) RunAndReturn(run func(resultID string) (*resultstore.MovieResult, string, bool)) *MockEditableJob_GetFileResultByResultID_Call {
	_c.Call.Return(run)
	return _c
}

// GetID provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) GetID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEditableJob_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type MockEditableJob_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *MockEditableJob_Expecter) GetID() *MockEditableJob_GetID_Call {
	return &MockEditableJob_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *MockEditableJob_GetID_Call) Run(run func()) *MockEditableJob_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditableJob_GetID_Call) Return(s string) *MockEditableJob_GetID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEditableJob_GetID_Call) RunAndReturn(run func() string) *MockEditableJob_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobStatus provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) GetJobStatus() models.JobStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetJobStatus")
	}

	var r0 models.JobStatus
	if returnFunc, ok := ret.Get(0).(func() models.JobStatus); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(models.JobStatus)
	}
	return r0
}

// MockEditableJob_GetJobStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobStatus'
type MockEditableJob_GetJobStatus_Call struct {
	*mock.Call
}

// GetJobStatus is a helper method to define mock.On call
func (_e *MockEditableJob_Expecter) GetJobStatus() *MockEditableJob_GetJobStatus_Call {
	return &MockEditableJob_GetJobStatus_Call{Call: _e.mock.On("GetJobStatus")}
}

func (_c *MockEditableJob_GetJobStatus_Call) Run(run func()) *MockEditableJob_GetJobStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditableJob_GetJobStatus_Call) Return(jobStatus models.JobStatus) *MockEditableJob_GetJobStatus_Call {
	_c.Call.Return(jobStatus)
	return _c
}

func (_c *MockEditableJob_GetJobStatus_Call) RunAndReturn(run func() models.JobStatus) *MockEditableJob_GetJobStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetMovieResult provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) GetMovieResult(filePath string) (*resultstore.MovieResult, error) {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieResult")
	}

	var r0 *resultstore.MovieResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*resultstore.MovieResult, error)); ok {
		return returnFunc(filePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *resultstore.MovieResult); ok {
		r0 = returnFunc(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resultstore.MovieResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEditableJob_GetMovieResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovieResult'
type MockEditableJob_GetMovieResult_Call struct {
	*mock.Call
}

// GetMovieResult is a helper method to define mock.On call
//   - filePath string
func (_e *MockEditableJob_Expecter) GetMovieResult(filePath any) *MockEditableJob_GetMovieResult_Call {
	return &MockEditableJob_GetMovieResult_Call{Call: _e.mock.On("GetMovieResult", filePath)}
}

func (_c *MockEditableJob_GetMovieResult_Call) Run(run func(filePath string)) *MockEditableJob_GetMovieResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEditableJob_GetMovieResult_Call) Return(movieResult *resultstore.MovieResult, err error) *MockEditableJob_GetMovieResult_Call {
	_c.Call.Return(movieResult, err)
	return _c
}

func (_c *MockEditableJob_GetMovieResult_Call) RunAndReturn(run func(filePath string) (*resultstore.MovieResult, error)) *MockEditableJob_GetMovieResult_Call {
	_c.Call.Return(run)
	return _c
}

// GetMovieResultsForMovieID provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) GetMovieResultsForMovieID(movieID string) []*resultstore.MovieResult {
	ret := _mock.Called(movieID)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieResultsForMovieID")
	}

	var r0 []*resultstore.MovieResult
	if returnFunc, ok := ret.Get(0).(func(string) []*resultstore.MovieResult); ok {
		r0 = returnFunc(movieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*resultstore.MovieResult)
		}
	}
	return r0
}

// MockEditableJob_GetMovieResultsForMovieID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovieResultsForMovieID'
type MockEditableJob_GetMovieResultsForMovieID_Call struct {
	*mock.Call
}

// GetMovieResultsForMovieID is a helper method to define mock.On call
//   - movieID string
func (_e *MockEditableJob_Expecter) GetMovieResultsForMovieID(movieID any) *MockEditableJob_GetMovieResultsForMovieID_Call {
	return &MockEditableJob_GetMovieResultsForMovieID_Call{Call: _e.mock.On("GetMovieResultsForMovieID", movieID)}
}

func (_c *MockEditableJob_GetMovieResultsForMovieID_Call) Run(run func(movieID string)) *MockEditableJob_GetMovieResultsForMovieID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEditableJob_GetMovieResultsForMovieID_Call) Return(movieResults []*resultstore.MovieResult) *MockEditableJob_GetMovieResultsForMovieID_Call {
	_c.Call.Return(movieResults)
	return _c
}

func (_c *MockEditableJob_GetMovieResultsForMovieID_Call) RunAndReturn(run func(movieID string) []*resultstore.MovieResult) *MockEditableJob_GetMovieResultsForMovieID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProvenance provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) GetProvenance(filePath string) *resultstore.ProvenanceData {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for GetProvenance")
	}

	var r0 *resultstore.ProvenanceData
	if returnFunc, ok := ret.Get(0).(func(string) *resultstore.ProvenanceData); ok {
		r0 = returnFunc(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resultstore.ProvenanceData)
		}
	}
	return r0
}

// MockEditableJob_GetProvenance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProvenance'
type MockEditableJob_GetProvenance_Call struct {
	*mock.Call
}

// GetProvenance is a helper method to define mock.On call
//   - filePath string
func (_e *MockEditableJob_Expecter) GetProvenance(filePath any) *MockEditableJob_GetProvenance_Call {
	return &MockEditableJob_GetProvenance_Call{Call: _e.mock.On("GetProvenance", filePath)}
}

func (_c *MockEditableJob_GetProvenance_Call) Run(run func(filePath string)) *MockEditableJob_GetProvenance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEditableJob_GetProvenance_Call) Return(provenanceData *resultstore.ProvenanceData) *MockEditableJob_GetProvenance_Call {
	_c.Call.Return(provenanceData)
	return _c
}

func (_c *MockEditableJob_GetProvenance_Call) RunAndReturn(run func(filePath string) *resultstore.ProvenanceData) *MockEditableJob_GetProvenance_Call {
	_c.Call.Return(run)
	return _c
}

// GetResults provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) GetResults() []resultstore.MovieResult {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResults")
	}

	var r0 []resultstore.MovieResult
	if returnFunc, ok := ret.Get(0).(func() []resultstore.MovieResult); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resultstore.MovieResult)
		}
	}
	return r0
}

// MockEditableJob_GetResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResults'
type MockEditableJob_GetResults_Call struct {
	*mock.Call
}

// GetResults is a helper method to define mock.On call
func (_e *MockEditableJob_Expecter) GetResults() *MockEditableJob_GetResults_Call {
	return &MockEditableJob_GetResults_Call{Call: _e.mock.On("GetResults")}
}

func (_c *MockEditableJob_GetResults_Call) Run(run func()) *MockEditableJob_GetResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditableJob_GetResults_Call) Return(movieResults []resultstore.MovieResult) *MockEditableJob_GetResults_Call {
	_c.Call.Return(movieResults)
	return _c
}

func (_c *MockEditableJob_GetResults_Call) RunAndReturn(run func() []resultstore.MovieResult) *MockEditableJob_GetResults_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) GetStatus() *worker.BatchJobStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 *worker.BatchJobStatus
	if returnFunc, ok := ret.Get(0).(func() *worker.BatchJobStatus); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*worker.BatchJobStatus)
		}
	}
	return r0
}

// MockEditableJob_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockEditableJob_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
func (_e *MockEditableJob_Expecter) GetStatus() *MockEditableJob_GetStatus_Call {
	return &MockEditableJob_GetStatus_Call{Call: _e.mock.On("GetStatus")}
}

func (_c *MockEditableJob_GetStatus_Call) Run(run func()) *MockEditableJob_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditableJob_GetStatus_Call) Return(batchJobStatus *worker.BatchJobStatus) *MockEditableJob_GetStatus_Call {
	_c.Call.Return(batchJobStatus)
	return _c
}

func (_c *MockEditableJob_GetStatus_Call) RunAndReturn(run func() *worker.BatchJobStatus) *MockEditableJob_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) Subscribe() worker.JobEventSubscriber {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 worker.JobEventSubscriber
	if returnFunc, ok := ret.Get(0).(func() worker.JobEventSubscriber); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(worker.JobEventSubscriber)
		}
	}
	return r0
}

// MockEditableJob_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockEditableJob_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
func (_e *MockEditableJob_Expecter) Subscribe() *MockEditableJob_Subscribe_Call {
	return &MockEditableJob_Subscribe_Call{Call: _e.mock.On("Subscribe")}
}

func (_c *MockEditableJob_Subscribe_Call) Run(run func()) *MockEditableJob_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditableJob_Subscribe_Call) Return(jobEventSubscriber worker.JobEventSubscriber) *MockEditableJob_Subscribe_Call {
	_c.Call.Return(jobEventSubscriber)
	return _c
}

func (_c *MockEditableJob_Subscribe_Call) RunAndReturn(run func() worker.JobEventSubscriber) *MockEditableJob_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMovie provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) UpdateMovie(ctx context.Context, filePath string, movie *models.Movie) error {
	ret := _mock.Called(ctx, filePath, movie)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMovie")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *models.Movie) error); ok {
		r0 = returnFunc(ctx, filePath, movie)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEditableJob_UpdateMovie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMovie'
type MockEditableJob_UpdateMovie_Call struct {
	*mock.Call
}

// UpdateMovie is a helper method to define mock.On call
//   - ctx context.Context
//   - filePath string
//   - movie *models.Movie
func (_e *MockEditableJob_Expecter) UpdateMovie(ctx any, filePath any, movie any) *MockEditableJob_UpdateMovie_Call {
	return &MockEditableJob_UpdateMovie_Call{Call: _e.mock.On("UpdateMovie", ctx, filePath, movie)}
}

func (_c *MockEditableJob_UpdateMovie_Call) Run(run func(ctx context.Context, filePath string, movie *models.Movie)) *MockEditableJob_UpdateMovie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *models.Movie
		if args[2] != nil {
			arg2 = args[2].(*models.Movie)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEditableJob_UpdateMovie_Call) Return(err error) *MockEditableJob_UpdateMovie_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEditableJob_UpdateMovie_Call) RunAndReturn(run func(ctx context.Context, filePath string, movie *models.Movie) error) *MockEditableJob_UpdateMovie_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMovieFamily provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) UpdateMovieFamily(ctx context.Context, movieID string, resultID string, movie *models.Movie, opts worker.FamilySaveOptions) error {
	ret := _mock.Called(ctx, movieID, resultID, movie, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMovieFamily")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *models.Movie, worker.FamilySaveOptions) error); ok {
		r0 = returnFunc(ctx, movieID, resultID, movie, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEditableJob_UpdateMovieFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMovieFamily'
type MockEditableJob_UpdateMovieFamily_Call struct {
	*mock.Call
}

// UpdateMovieFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - movieID string
//   - resultID string
//   - movie *models.Movie
//   - opts worker.FamilySaveOptions
func (_e *MockEditableJob_Expecter) UpdateMovieFamily(ctx any, movieID any, resultID any, movie any, opts any) *MockEditableJob_UpdateMovieFamily_Call {
	return &MockEditableJob_UpdateMovieFamily_Call{Call: _e.mock.On("UpdateMovieFamily", ctx, movieID, resultID, movie, opts)}
}

func (_c *MockEditableJob_UpdateMovieFamily_Call) Run(run func(ctx context.Context, movieID string, resultID string, movie *models.Movie, opts worker.FamilySaveOptions)) *MockEditableJob_UpdateMovieFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *models.Movie
		if args[3] != nil {
			arg3 = args[3].(*models.Movie)
		}
		var arg4 worker.FamilySaveOptions
		if args[4] != nil {
			arg4 = args[4].(worker.FamilySaveOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockEditableJob_UpdateMovieFamily_Call) Return(err error) *MockEditableJob_UpdateMovieFamily_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEditableJob_UpdateMovieFamily_Call) RunAndReturn(run func(ctx context.Context, movieID string, resultID string, movie *models.Movie, opts worker.FamilySaveOptions) error) *MockEditableJob_UpdateMovieFamily_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMovieFamilyWithEcho provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) UpdateMovieFamilyWithEcho(ctx context.Context, movieID string, resultID string, movie *models.Movie, opts worker.FamilySaveOptions) (*uint64, map[string]uint64, error) {
	ret := _mock.Called(ctx, movieID, resultID, movie, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMovieFamilyWithEcho")
	}

	var r0 *uint64
	var r1 map[string]uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *models.Movie, worker.FamilySaveOptions) (*uint64, map[string]uint64, error)); ok {
		return returnFunc(ctx, movieID, resultID, movie, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *models.Movie, worker.FamilySaveOptions) *uint64); ok {
		r0 = returnFunc(ctx, movieID, resultID, movie, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *models.Movie, worker.FamilySaveOptions) map[string]uint64); ok {
		r1 = returnFunc(ctx, movieID, resultID, movie, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]uint64)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, *models.Movie, worker.FamilySaveOptions) error); ok {
		r2 = returnFunc(ctx, movieID, resultID, movie, opts)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockEditableJob_UpdateMovieFamilyWithEcho_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMovieFamilyWithEcho'
type MockEditableJob_UpdateMovieFamilyWithEcho_Call struct {
	*mock.Call
}

// UpdateMovieFamilyWithEcho is a helper method to define mock.On call
//   - ctx context.Context
//   - movieID string
//   - resultID string
//   - movie *models.Movie
//   - opts worker.FamilySaveOptions
func (_e *MockEditableJob_Expecter) UpdateMovieFamilyWithEcho(ctx any, movieID any, resultID any, movie any, opts any) *MockEditableJob_UpdateMovieFamilyWithEcho_Call {
	return &MockEditableJob_UpdateMovieFamilyWithEcho_Call{Call: _e.mock.On("UpdateMovieFamilyWithEcho", ctx, movieID, resultID, movie, opts)}
}

func (_c *MockEditableJob_UpdateMovieFamilyWithEcho_Call) Run(run func(ctx context.Context, movieID string, resultID string, movie *models.Movie, opts worker.FamilySaveOptions)) *MockEditableJob_UpdateMovieFamilyWithEcho_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *models.Movie
		if args[3] != nil {
			arg3 = args[3].(*models.Movie)
		}
		var arg4 worker.FamilySaveOptions
		if args[4] != nil {
			arg4 = args[4].(worker.FamilySaveOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockEditableJob_UpdateMovieFamilyWithEcho_Call) Return(v *uint64, stringToUint64 map[string]uint64, err error) *MockEditableJob_UpdateMovieFamilyWithEcho_Call {
	_c.Call.Return(v, stringToUint64, err)
	return _c
}

func (_c *MockEditableJob_UpdateMovieFamilyWithEcho_Call) RunAndReturn(run func(ctx context.Context, movieID string, resultID string, movie *models.Movie, opts worker.FamilySaveOptions) (*uint64, map[string]uint64, error)) *MockEditableJob_UpdateMovieFamilyWithEcho_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePosterCrop provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) UpdatePosterCrop(movieID string, croppedURL string, bounds *models.CropBounds, sourceFull bool) error {
	ret := _mock.Called(movieID, croppedURL, bounds, sourceFull)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePosterCrop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *models.CropBounds, bool) error); ok {
		r0 = returnFunc(movieID, croppedURL, bounds, sourceFull)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEditableJob_UpdatePosterCrop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePosterCrop'
type MockEditableJob_UpdatePosterCrop_Call struct {
	*mock.Call
}

// UpdatePosterCrop is a helper method to define mock.On call
//   - movieID string
//   - croppedURL string
//   - bounds *models.CropBounds
//   - sourceFull bool
func (_e *MockEditableJob_Expecter) UpdatePosterCrop(movieID any, croppedURL any, bounds any, sourceFull any) *MockEditableJob_UpdatePosterCrop_Call {
	return &MockEditableJob_UpdatePosterCrop_Call{Call: _e.mock.On("UpdatePosterCrop", movieID, croppedURL, bounds, sourceFull)}
}

func (_c *MockEditableJob_UpdatePosterCrop_Call) Run(run func(movieID string, croppedURL string, bounds *models.CropBounds, sourceFull bool)) *MockEditableJob_UpdatePosterCrop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *models.CropBounds
		if args[2] != nil {
			arg2 = args[2].(*models.CropBounds)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEditableJob_UpdatePosterCrop_Call) Return(err error) *MockEditableJob_UpdatePosterCrop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEditableJob_UpdatePosterCrop_Call) RunAndReturn(run func(movieID string, croppedURL string, bounds *models.CropBounds, sourceFull bool) error) *MockEditableJob_UpdatePosterCrop_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePosterFromURL provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) UpdatePosterFromURL(ctx context.Context, movieID string, posterURL string, croppedURL string) error {
	ret := _mock.Called(ctx, movieID, posterURL, croppedURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePosterFromURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, movieID, posterURL, croppedURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEditableJob_UpdatePosterFromURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePosterFromURL'
type MockEditableJob_UpdatePosterFromURL_Call struct {
	*mock.Call
}

// UpdatePosterFromURL is a helper method to define mock.On call
//   - ctx context.Context
//   - movieID string
//   - posterURL string
//   - croppedURL string
func (_e *MockEditableJob_Expecter) UpdatePosterFromURL(ctx any, movieID any, posterURL any, croppedURL any) *MockEditableJob_UpdatePosterFromURL_Call {
	return &MockEditableJob_UpdatePosterFromURL_Call{Call: _e.mock.On("UpdatePosterFromURL", ctx, movieID, posterURL, croppedURL)}
}

func (_c *MockEditableJob_UpdatePosterFromURL_Call) Run(run func(ctx context.Context, movieID string, posterURL string, croppedURL string)) *MockEditableJob_UpdatePosterFromURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEditableJob_UpdatePosterFromURL_Call) Return(err error) *MockEditableJob_UpdatePosterFromURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEditableJob_UpdatePosterFromURL_Call) RunAndReturn(run func(ctx context.Context, movieID string, posterURL string, croppedURL string) error) *MockEditableJob_UpdatePosterFromURL_Call {
	_c.Call.Return(run)
	return _c
}

// WithMovieEditLock provides a mock function for the type MockEditableJob
func (_mock *MockEditableJob) WithMovieEditLock(movieID string, fn func(m *worker.LockedMovieOps) error) error {
	ret := _mock.Called(movieID, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithMovieEditLock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, func(m *worker.LockedMovieOps) error) error); ok {
		r0 = returnFunc(movieID, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEditableJob_WithMovieEditLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithMovieEditLock'
type MockEditableJob_WithMovieEditLock_Call struct {
	*mock.Call
}

// WithMovieEditLock is a helper method to define mock.On call
//   - movieID string
//   - fn func(m *worker.LockedMovieOps) error
func (_e *MockEditableJob_Expecter) WithMovieEditLock(movieID any, fn any) *MockEditableJob_WithMovieEditLock_Call {
	return &MockEditableJob_WithMovieEditLock_Call{Call: _e.mock.On("WithMovieEditLock", movieID, fn)}
}

func (_c *MockEditableJob_WithMovieEditLock_Call) Run(run func(movieID string, fn func(m *worker.LockedMovieOps) error)) *MockEditableJob_WithMovieEditLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func(m *worker.LockedMovieOps) error
		if args[1] != nil {
			arg1 = args[1].(func(m *worker.LockedMovieOps) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEditableJob_WithMovieEditLock_Call) Return(err error) *MockEditableJob_WithMovieEditLock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEditableJob_WithMovieEditLock_Call) RunAndReturn(run func(movieID string, fn func(m *worker.LockedMovieOps) error) error) *MockEditableJob_WithMovieEditLock_Call {
	_c.Call.Return(run)
	return _c
}
